// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class AppPassword extends pulumi.CustomResource {
    /**
     * Get an existing AppPassword resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: AppPasswordState, opts?: pulumi.CustomResourceOptions): AppPassword {
        return new AppPassword(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'materialize:index/appPassword:AppPassword';

    /**
     * Returns true if the given object is an instance of AppPassword.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is AppPassword {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === AppPassword.__pulumiType;
    }

    declare public readonly appPasswordId: pulumi.Output<string>;
    /**
     * The time at which the app password was created.
     */
    declare public /*out*/ readonly createdAt: pulumi.Output<string>;
    /**
     * A human-readable name for the app password.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The value of the app password.
     */
    declare public /*out*/ readonly password: pulumi.Output<string>;
    /**
     * The roles to assign to the app password. Allowed values are 'Member' and 'Admin'. Only valid with service-type app passwords.
     */
    declare public readonly roles: pulumi.Output<string[] | undefined>;
    declare public /*out*/ readonly secret: pulumi.Output<string>;
    /**
     * The type of the app password: personal or service.
     */
    declare public readonly type: pulumi.Output<string | undefined>;
    /**
     * The user to associate with the app password. Only valid with service-type app passwords.
     */
    declare public readonly user: pulumi.Output<string | undefined>;

    /**
     * Create a AppPassword resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: AppPasswordArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: AppPasswordArgs | AppPasswordState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as AppPasswordState | undefined;
            resourceInputs["appPasswordId"] = state?.appPasswordId;
            resourceInputs["createdAt"] = state?.createdAt;
            resourceInputs["name"] = state?.name;
            resourceInputs["password"] = state?.password;
            resourceInputs["roles"] = state?.roles;
            resourceInputs["secret"] = state?.secret;
            resourceInputs["type"] = state?.type;
            resourceInputs["user"] = state?.user;
        } else {
            const args = argsOrState as AppPasswordArgs | undefined;
            resourceInputs["appPasswordId"] = args?.appPasswordId;
            resourceInputs["name"] = args?.name;
            resourceInputs["roles"] = args?.roles;
            resourceInputs["type"] = args?.type;
            resourceInputs["user"] = args?.user;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["password"] = undefined /*out*/;
            resourceInputs["secret"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["password", "secret"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(AppPassword.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering AppPassword resources.
 */
export interface AppPasswordState {
    appPasswordId?: pulumi.Input<string>;
    /**
     * The time at which the app password was created.
     */
    createdAt?: pulumi.Input<string>;
    /**
     * A human-readable name for the app password.
     */
    name?: pulumi.Input<string>;
    /**
     * The value of the app password.
     */
    password?: pulumi.Input<string>;
    /**
     * The roles to assign to the app password. Allowed values are 'Member' and 'Admin'. Only valid with service-type app passwords.
     */
    roles?: pulumi.Input<pulumi.Input<string>[]>;
    secret?: pulumi.Input<string>;
    /**
     * The type of the app password: personal or service.
     */
    type?: pulumi.Input<string>;
    /**
     * The user to associate with the app password. Only valid with service-type app passwords.
     */
    user?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a AppPassword resource.
 */
export interface AppPasswordArgs {
    appPasswordId?: pulumi.Input<string>;
    /**
     * A human-readable name for the app password.
     */
    name?: pulumi.Input<string>;
    /**
     * The roles to assign to the app password. Allowed values are 'Member' and 'Admin'. Only valid with service-type app passwords.
     */
    roles?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The type of the app password: personal or service.
     */
    type?: pulumi.Input<string>;
    /**
     * The user to associate with the app password. Only valid with service-type app passwords.
     */
    user?: pulumi.Input<string>;
}
