// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class ConnectionAwsPrivatelink extends pulumi.CustomResource {
    /**
     * Get an existing ConnectionAwsPrivatelink resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ConnectionAwsPrivatelinkState, opts?: pulumi.CustomResourceOptions): ConnectionAwsPrivatelink {
        return new ConnectionAwsPrivatelink(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'materialize:index/connectionAwsPrivatelink:ConnectionAwsPrivatelink';

    /**
     * Returns true if the given object is an instance of ConnectionAwsPrivatelink.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ConnectionAwsPrivatelink {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ConnectionAwsPrivatelink.__pulumiType;
    }

    /**
     * The availability zones of the AWS PrivateLink service.
     */
    declare public readonly availabilityZones: pulumi.Output<string[]>;
    /**
     * Comment on an object in the database.
     */
    declare public readonly comment: pulumi.Output<string | undefined>;
    declare public readonly connectionAwsPrivatelinkId: pulumi.Output<string>;
    /**
     * The identifier for the connection database in Materialize. Defaults to `MZ_DATABASE` environment variable if set or <span pulumi-lang-nodejs="`materialize`" pulumi-lang-dotnet="`Materialize`" pulumi-lang-go="`materialize`" pulumi-lang-python="`materialize`" pulumi-lang-yaml="`materialize`" pulumi-lang-java="`materialize`">`materialize`</span> if environment variable is not set.
     */
    declare public readonly databaseName: pulumi.Output<string | undefined>;
    /**
     * The identifier for the connection.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The owernship role of the object.
     */
    declare public readonly ownershipRole: pulumi.Output<string>;
    /**
     * The principal of the AWS PrivateLink service.
     */
    declare public /*out*/ readonly principal: pulumi.Output<string>;
    /**
     * The fully qualified name of the connection.
     */
    declare public /*out*/ readonly qualifiedSqlName: pulumi.Output<string>;
    /**
     * The region to use for the resource connection. If not set, the default region is used.
     */
    declare public readonly region: pulumi.Output<string>;
    /**
     * The identifier for the connection schema in Materialize. Defaults to <span pulumi-lang-nodejs="`public`" pulumi-lang-dotnet="`Public`" pulumi-lang-go="`public`" pulumi-lang-python="`public`" pulumi-lang-yaml="`public`" pulumi-lang-java="`public`">`public`</span>.
     */
    declare public readonly schemaName: pulumi.Output<string | undefined>;
    /**
     * The name of the AWS PrivateLink service.
     */
    declare public readonly serviceName: pulumi.Output<string>;
    /**
     * If the connection should wait for validation.
     */
    declare public readonly validate: pulumi.Output<boolean | undefined>;

    /**
     * Create a ConnectionAwsPrivatelink resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ConnectionAwsPrivatelinkArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ConnectionAwsPrivatelinkArgs | ConnectionAwsPrivatelinkState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ConnectionAwsPrivatelinkState | undefined;
            resourceInputs["availabilityZones"] = state?.availabilityZones;
            resourceInputs["comment"] = state?.comment;
            resourceInputs["connectionAwsPrivatelinkId"] = state?.connectionAwsPrivatelinkId;
            resourceInputs["databaseName"] = state?.databaseName;
            resourceInputs["name"] = state?.name;
            resourceInputs["ownershipRole"] = state?.ownershipRole;
            resourceInputs["principal"] = state?.principal;
            resourceInputs["qualifiedSqlName"] = state?.qualifiedSqlName;
            resourceInputs["region"] = state?.region;
            resourceInputs["schemaName"] = state?.schemaName;
            resourceInputs["serviceName"] = state?.serviceName;
            resourceInputs["validate"] = state?.validate;
        } else {
            const args = argsOrState as ConnectionAwsPrivatelinkArgs | undefined;
            if (args?.availabilityZones === undefined && !opts.urn) {
                throw new Error("Missing required property 'availabilityZones'");
            }
            if (args?.serviceName === undefined && !opts.urn) {
                throw new Error("Missing required property 'serviceName'");
            }
            resourceInputs["availabilityZones"] = args?.availabilityZones;
            resourceInputs["comment"] = args?.comment;
            resourceInputs["connectionAwsPrivatelinkId"] = args?.connectionAwsPrivatelinkId;
            resourceInputs["databaseName"] = args?.databaseName;
            resourceInputs["name"] = args?.name;
            resourceInputs["ownershipRole"] = args?.ownershipRole;
            resourceInputs["region"] = args?.region;
            resourceInputs["schemaName"] = args?.schemaName;
            resourceInputs["serviceName"] = args?.serviceName;
            resourceInputs["validate"] = args?.validate;
            resourceInputs["principal"] = undefined /*out*/;
            resourceInputs["qualifiedSqlName"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["principal"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(ConnectionAwsPrivatelink.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering ConnectionAwsPrivatelink resources.
 */
export interface ConnectionAwsPrivatelinkState {
    /**
     * The availability zones of the AWS PrivateLink service.
     */
    availabilityZones?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Comment on an object in the database.
     */
    comment?: pulumi.Input<string>;
    connectionAwsPrivatelinkId?: pulumi.Input<string>;
    /**
     * The identifier for the connection database in Materialize. Defaults to `MZ_DATABASE` environment variable if set or <span pulumi-lang-nodejs="`materialize`" pulumi-lang-dotnet="`Materialize`" pulumi-lang-go="`materialize`" pulumi-lang-python="`materialize`" pulumi-lang-yaml="`materialize`" pulumi-lang-java="`materialize`">`materialize`</span> if environment variable is not set.
     */
    databaseName?: pulumi.Input<string>;
    /**
     * The identifier for the connection.
     */
    name?: pulumi.Input<string>;
    /**
     * The owernship role of the object.
     */
    ownershipRole?: pulumi.Input<string>;
    /**
     * The principal of the AWS PrivateLink service.
     */
    principal?: pulumi.Input<string>;
    /**
     * The fully qualified name of the connection.
     */
    qualifiedSqlName?: pulumi.Input<string>;
    /**
     * The region to use for the resource connection. If not set, the default region is used.
     */
    region?: pulumi.Input<string>;
    /**
     * The identifier for the connection schema in Materialize. Defaults to <span pulumi-lang-nodejs="`public`" pulumi-lang-dotnet="`Public`" pulumi-lang-go="`public`" pulumi-lang-python="`public`" pulumi-lang-yaml="`public`" pulumi-lang-java="`public`">`public`</span>.
     */
    schemaName?: pulumi.Input<string>;
    /**
     * The name of the AWS PrivateLink service.
     */
    serviceName?: pulumi.Input<string>;
    /**
     * If the connection should wait for validation.
     */
    validate?: pulumi.Input<boolean>;
}

/**
 * The set of arguments for constructing a ConnectionAwsPrivatelink resource.
 */
export interface ConnectionAwsPrivatelinkArgs {
    /**
     * The availability zones of the AWS PrivateLink service.
     */
    availabilityZones: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Comment on an object in the database.
     */
    comment?: pulumi.Input<string>;
    connectionAwsPrivatelinkId?: pulumi.Input<string>;
    /**
     * The identifier for the connection database in Materialize. Defaults to `MZ_DATABASE` environment variable if set or <span pulumi-lang-nodejs="`materialize`" pulumi-lang-dotnet="`Materialize`" pulumi-lang-go="`materialize`" pulumi-lang-python="`materialize`" pulumi-lang-yaml="`materialize`" pulumi-lang-java="`materialize`">`materialize`</span> if environment variable is not set.
     */
    databaseName?: pulumi.Input<string>;
    /**
     * The identifier for the connection.
     */
    name?: pulumi.Input<string>;
    /**
     * The owernship role of the object.
     */
    ownershipRole?: pulumi.Input<string>;
    /**
     * The region to use for the resource connection. If not set, the default region is used.
     */
    region?: pulumi.Input<string>;
    /**
     * The identifier for the connection schema in Materialize. Defaults to <span pulumi-lang-nodejs="`public`" pulumi-lang-dotnet="`Public`" pulumi-lang-go="`public`" pulumi-lang-python="`public`" pulumi-lang-yaml="`public`" pulumi-lang-java="`public`">`public`</span>.
     */
    schemaName?: pulumi.Input<string>;
    /**
     * The name of the AWS PrivateLink service.
     */
    serviceName: pulumi.Input<string>;
    /**
     * If the connection should wait for validation.
     */
    validate?: pulumi.Input<boolean>;
}
