// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class ConnectionAws extends pulumi.CustomResource {
    /**
     * Get an existing ConnectionAws resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ConnectionAwsState, opts?: pulumi.CustomResourceOptions): ConnectionAws {
        return new ConnectionAws(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'materialize:index/connectionAws:ConnectionAws';

    /**
     * Returns true if the given object is an instance of ConnectionAws.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ConnectionAws {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ConnectionAws.__pulumiType;
    }

    /**
     * The access key ID to connect with.. Can be supplied as either free text using <span pulumi-lang-nodejs="`text`" pulumi-lang-dotnet="`Text`" pulumi-lang-go="`text`" pulumi-lang-python="`text`" pulumi-lang-yaml="`text`" pulumi-lang-java="`text`">`text`</span> or reference to a secret object using <span pulumi-lang-nodejs="`secret`" pulumi-lang-dotnet="`Secret`" pulumi-lang-go="`secret`" pulumi-lang-python="`secret`" pulumi-lang-yaml="`secret`" pulumi-lang-java="`secret`">`secret`</span>.
     */
    declare public readonly accessKeyId: pulumi.Output<outputs.ConnectionAwsAccessKeyId | undefined>;
    /**
     * The Amazon Resource Name (ARN) of the IAM role to assume.
     */
    declare public readonly assumeRoleArn: pulumi.Output<string | undefined>;
    /**
     * The session name to use when assuming the role.
     */
    declare public readonly assumeRoleSessionName: pulumi.Output<string | undefined>;
    /**
     * The AWS region to connect to.
     */
    declare public readonly awsRegion: pulumi.Output<string | undefined>;
    /**
     * Comment on an object in the database.
     */
    declare public readonly comment: pulumi.Output<string | undefined>;
    declare public readonly connectionAwsId: pulumi.Output<string>;
    /**
     * The identifier for the connection database in Materialize. Defaults to `MZ_DATABASE` environment variable if set or <span pulumi-lang-nodejs="`materialize`" pulumi-lang-dotnet="`Materialize`" pulumi-lang-go="`materialize`" pulumi-lang-python="`materialize`" pulumi-lang-yaml="`materialize`" pulumi-lang-java="`materialize`">`materialize`</span> if environment variable is not set.
     */
    declare public readonly databaseName: pulumi.Output<string | undefined>;
    /**
     * Override the default AWS endpoint URL.
     */
    declare public readonly endpoint: pulumi.Output<string | undefined>;
    /**
     * The external ID used for trust relationship when<span pulumi-lang-nodejs=" assumeRoleArn " pulumi-lang-dotnet=" AssumeRoleArn " pulumi-lang-go=" assumeRoleArn " pulumi-lang-python=" assume_role_arn " pulumi-lang-yaml=" assumeRoleArn " pulumi-lang-java=" assumeRoleArn "> assume_role_arn </span>is specified. This is a read-only attribute that is automatically generated.
     */
    declare public /*out*/ readonly externalId: pulumi.Output<string>;
    /**
     * The identifier for the connection.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The owernship role of the object.
     */
    declare public readonly ownershipRole: pulumi.Output<string>;
    /**
     * The fully qualified name of the connection.
     */
    declare public /*out*/ readonly qualifiedSqlName: pulumi.Output<string>;
    /**
     * The region to use for the resource connection. If not set, the default region is used.
     */
    declare public readonly region: pulumi.Output<string>;
    /**
     * The identifier for the connection schema in Materialize. Defaults to <span pulumi-lang-nodejs="`public`" pulumi-lang-dotnet="`Public`" pulumi-lang-go="`public`" pulumi-lang-python="`public`" pulumi-lang-yaml="`public`" pulumi-lang-java="`public`">`public`</span>.
     */
    declare public readonly schemaName: pulumi.Output<string | undefined>;
    /**
     * The secret access key corresponding to the specified access key ID.
     */
    declare public readonly secretAccessKey: pulumi.Output<outputs.ConnectionAwsSecretAccessKey | undefined>;
    /**
     * The session token corresponding to the specified access key ID.. Can be supplied as either free text using <span pulumi-lang-nodejs="`text`" pulumi-lang-dotnet="`Text`" pulumi-lang-go="`text`" pulumi-lang-python="`text`" pulumi-lang-yaml="`text`" pulumi-lang-java="`text`">`text`</span> or reference to a secret object using <span pulumi-lang-nodejs="`secret`" pulumi-lang-dotnet="`Secret`" pulumi-lang-go="`secret`" pulumi-lang-python="`secret`" pulumi-lang-yaml="`secret`" pulumi-lang-java="`secret`">`secret`</span>.
     */
    declare public readonly sessionToken: pulumi.Output<outputs.ConnectionAwsSessionToken | undefined>;
    /**
     * If the connection should wait for validation.
     */
    declare public readonly validate: pulumi.Output<boolean | undefined>;

    /**
     * Create a ConnectionAws resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ConnectionAwsArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ConnectionAwsArgs | ConnectionAwsState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ConnectionAwsState | undefined;
            resourceInputs["accessKeyId"] = state?.accessKeyId;
            resourceInputs["assumeRoleArn"] = state?.assumeRoleArn;
            resourceInputs["assumeRoleSessionName"] = state?.assumeRoleSessionName;
            resourceInputs["awsRegion"] = state?.awsRegion;
            resourceInputs["comment"] = state?.comment;
            resourceInputs["connectionAwsId"] = state?.connectionAwsId;
            resourceInputs["databaseName"] = state?.databaseName;
            resourceInputs["endpoint"] = state?.endpoint;
            resourceInputs["externalId"] = state?.externalId;
            resourceInputs["name"] = state?.name;
            resourceInputs["ownershipRole"] = state?.ownershipRole;
            resourceInputs["qualifiedSqlName"] = state?.qualifiedSqlName;
            resourceInputs["region"] = state?.region;
            resourceInputs["schemaName"] = state?.schemaName;
            resourceInputs["secretAccessKey"] = state?.secretAccessKey;
            resourceInputs["sessionToken"] = state?.sessionToken;
            resourceInputs["validate"] = state?.validate;
        } else {
            const args = argsOrState as ConnectionAwsArgs | undefined;
            resourceInputs["accessKeyId"] = args?.accessKeyId;
            resourceInputs["assumeRoleArn"] = args?.assumeRoleArn;
            resourceInputs["assumeRoleSessionName"] = args?.assumeRoleSessionName;
            resourceInputs["awsRegion"] = args?.awsRegion;
            resourceInputs["comment"] = args?.comment;
            resourceInputs["connectionAwsId"] = args?.connectionAwsId;
            resourceInputs["databaseName"] = args?.databaseName;
            resourceInputs["endpoint"] = args?.endpoint;
            resourceInputs["name"] = args?.name;
            resourceInputs["ownershipRole"] = args?.ownershipRole;
            resourceInputs["region"] = args?.region;
            resourceInputs["schemaName"] = args?.schemaName;
            resourceInputs["secretAccessKey"] = args?.secretAccessKey;
            resourceInputs["sessionToken"] = args?.sessionToken;
            resourceInputs["validate"] = args?.validate;
            resourceInputs["externalId"] = undefined /*out*/;
            resourceInputs["qualifiedSqlName"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ConnectionAws.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering ConnectionAws resources.
 */
export interface ConnectionAwsState {
    /**
     * The access key ID to connect with.. Can be supplied as either free text using <span pulumi-lang-nodejs="`text`" pulumi-lang-dotnet="`Text`" pulumi-lang-go="`text`" pulumi-lang-python="`text`" pulumi-lang-yaml="`text`" pulumi-lang-java="`text`">`text`</span> or reference to a secret object using <span pulumi-lang-nodejs="`secret`" pulumi-lang-dotnet="`Secret`" pulumi-lang-go="`secret`" pulumi-lang-python="`secret`" pulumi-lang-yaml="`secret`" pulumi-lang-java="`secret`">`secret`</span>.
     */
    accessKeyId?: pulumi.Input<inputs.ConnectionAwsAccessKeyId>;
    /**
     * The Amazon Resource Name (ARN) of the IAM role to assume.
     */
    assumeRoleArn?: pulumi.Input<string>;
    /**
     * The session name to use when assuming the role.
     */
    assumeRoleSessionName?: pulumi.Input<string>;
    /**
     * The AWS region to connect to.
     */
    awsRegion?: pulumi.Input<string>;
    /**
     * Comment on an object in the database.
     */
    comment?: pulumi.Input<string>;
    connectionAwsId?: pulumi.Input<string>;
    /**
     * The identifier for the connection database in Materialize. Defaults to `MZ_DATABASE` environment variable if set or <span pulumi-lang-nodejs="`materialize`" pulumi-lang-dotnet="`Materialize`" pulumi-lang-go="`materialize`" pulumi-lang-python="`materialize`" pulumi-lang-yaml="`materialize`" pulumi-lang-java="`materialize`">`materialize`</span> if environment variable is not set.
     */
    databaseName?: pulumi.Input<string>;
    /**
     * Override the default AWS endpoint URL.
     */
    endpoint?: pulumi.Input<string>;
    /**
     * The external ID used for trust relationship when<span pulumi-lang-nodejs=" assumeRoleArn " pulumi-lang-dotnet=" AssumeRoleArn " pulumi-lang-go=" assumeRoleArn " pulumi-lang-python=" assume_role_arn " pulumi-lang-yaml=" assumeRoleArn " pulumi-lang-java=" assumeRoleArn "> assume_role_arn </span>is specified. This is a read-only attribute that is automatically generated.
     */
    externalId?: pulumi.Input<string>;
    /**
     * The identifier for the connection.
     */
    name?: pulumi.Input<string>;
    /**
     * The owernship role of the object.
     */
    ownershipRole?: pulumi.Input<string>;
    /**
     * The fully qualified name of the connection.
     */
    qualifiedSqlName?: pulumi.Input<string>;
    /**
     * The region to use for the resource connection. If not set, the default region is used.
     */
    region?: pulumi.Input<string>;
    /**
     * The identifier for the connection schema in Materialize. Defaults to <span pulumi-lang-nodejs="`public`" pulumi-lang-dotnet="`Public`" pulumi-lang-go="`public`" pulumi-lang-python="`public`" pulumi-lang-yaml="`public`" pulumi-lang-java="`public`">`public`</span>.
     */
    schemaName?: pulumi.Input<string>;
    /**
     * The secret access key corresponding to the specified access key ID.
     */
    secretAccessKey?: pulumi.Input<inputs.ConnectionAwsSecretAccessKey>;
    /**
     * The session token corresponding to the specified access key ID.. Can be supplied as either free text using <span pulumi-lang-nodejs="`text`" pulumi-lang-dotnet="`Text`" pulumi-lang-go="`text`" pulumi-lang-python="`text`" pulumi-lang-yaml="`text`" pulumi-lang-java="`text`">`text`</span> or reference to a secret object using <span pulumi-lang-nodejs="`secret`" pulumi-lang-dotnet="`Secret`" pulumi-lang-go="`secret`" pulumi-lang-python="`secret`" pulumi-lang-yaml="`secret`" pulumi-lang-java="`secret`">`secret`</span>.
     */
    sessionToken?: pulumi.Input<inputs.ConnectionAwsSessionToken>;
    /**
     * If the connection should wait for validation.
     */
    validate?: pulumi.Input<boolean>;
}

/**
 * The set of arguments for constructing a ConnectionAws resource.
 */
export interface ConnectionAwsArgs {
    /**
     * The access key ID to connect with.. Can be supplied as either free text using <span pulumi-lang-nodejs="`text`" pulumi-lang-dotnet="`Text`" pulumi-lang-go="`text`" pulumi-lang-python="`text`" pulumi-lang-yaml="`text`" pulumi-lang-java="`text`">`text`</span> or reference to a secret object using <span pulumi-lang-nodejs="`secret`" pulumi-lang-dotnet="`Secret`" pulumi-lang-go="`secret`" pulumi-lang-python="`secret`" pulumi-lang-yaml="`secret`" pulumi-lang-java="`secret`">`secret`</span>.
     */
    accessKeyId?: pulumi.Input<inputs.ConnectionAwsAccessKeyId>;
    /**
     * The Amazon Resource Name (ARN) of the IAM role to assume.
     */
    assumeRoleArn?: pulumi.Input<string>;
    /**
     * The session name to use when assuming the role.
     */
    assumeRoleSessionName?: pulumi.Input<string>;
    /**
     * The AWS region to connect to.
     */
    awsRegion?: pulumi.Input<string>;
    /**
     * Comment on an object in the database.
     */
    comment?: pulumi.Input<string>;
    connectionAwsId?: pulumi.Input<string>;
    /**
     * The identifier for the connection database in Materialize. Defaults to `MZ_DATABASE` environment variable if set or <span pulumi-lang-nodejs="`materialize`" pulumi-lang-dotnet="`Materialize`" pulumi-lang-go="`materialize`" pulumi-lang-python="`materialize`" pulumi-lang-yaml="`materialize`" pulumi-lang-java="`materialize`">`materialize`</span> if environment variable is not set.
     */
    databaseName?: pulumi.Input<string>;
    /**
     * Override the default AWS endpoint URL.
     */
    endpoint?: pulumi.Input<string>;
    /**
     * The identifier for the connection.
     */
    name?: pulumi.Input<string>;
    /**
     * The owernship role of the object.
     */
    ownershipRole?: pulumi.Input<string>;
    /**
     * The region to use for the resource connection. If not set, the default region is used.
     */
    region?: pulumi.Input<string>;
    /**
     * The identifier for the connection schema in Materialize. Defaults to <span pulumi-lang-nodejs="`public`" pulumi-lang-dotnet="`Public`" pulumi-lang-go="`public`" pulumi-lang-python="`public`" pulumi-lang-yaml="`public`" pulumi-lang-java="`public`">`public`</span>.
     */
    schemaName?: pulumi.Input<string>;
    /**
     * The secret access key corresponding to the specified access key ID.
     */
    secretAccessKey?: pulumi.Input<inputs.ConnectionAwsSecretAccessKey>;
    /**
     * The session token corresponding to the specified access key ID.. Can be supplied as either free text using <span pulumi-lang-nodejs="`text`" pulumi-lang-dotnet="`Text`" pulumi-lang-go="`text`" pulumi-lang-python="`text`" pulumi-lang-yaml="`text`" pulumi-lang-java="`text`">`text`</span> or reference to a secret object using <span pulumi-lang-nodejs="`secret`" pulumi-lang-dotnet="`Secret`" pulumi-lang-go="`secret`" pulumi-lang-python="`secret`" pulumi-lang-yaml="`secret`" pulumi-lang-java="`secret`">`secret`</span>.
     */
    sessionToken?: pulumi.Input<inputs.ConnectionAwsSessionToken>;
    /**
     * If the connection should wait for validation.
     */
    validate?: pulumi.Input<boolean>;
}
