// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class ConnectionPostgres extends pulumi.CustomResource {
    /**
     * Get an existing ConnectionPostgres resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ConnectionPostgresState, opts?: pulumi.CustomResourceOptions): ConnectionPostgres {
        return new ConnectionPostgres(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'materialize:index/connectionPostgres:ConnectionPostgres';

    /**
     * Returns true if the given object is an instance of ConnectionPostgres.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ConnectionPostgres {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ConnectionPostgres.__pulumiType;
    }

    /**
     * The AWS PrivateLink configuration for the Postgres database.
     */
    declare public readonly awsPrivatelink: pulumi.Output<outputs.ConnectionPostgresAwsPrivatelink | undefined>;
    /**
     * Comment on an object in the database.
     */
    declare public readonly comment: pulumi.Output<string | undefined>;
    declare public readonly connectionPostgresId: pulumi.Output<string>;
    /**
     * The target Postgres database.
     */
    declare public readonly database: pulumi.Output<string>;
    /**
     * The identifier for the connection database in Materialize. Defaults to `MZ_DATABASE` environment variable if set or <span pulumi-lang-nodejs="`materialize`" pulumi-lang-dotnet="`Materialize`" pulumi-lang-go="`materialize`" pulumi-lang-python="`materialize`" pulumi-lang-yaml="`materialize`" pulumi-lang-java="`materialize`">`materialize`</span> if environment variable is not set.
     */
    declare public readonly databaseName: pulumi.Output<string | undefined>;
    /**
     * The Postgres database hostname.
     */
    declare public readonly host: pulumi.Output<string>;
    /**
     * The identifier for the connection.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The owernship role of the object.
     */
    declare public readonly ownershipRole: pulumi.Output<string>;
    /**
     * The Postgres database password.
     */
    declare public readonly password: pulumi.Output<outputs.ConnectionPostgresPassword | undefined>;
    /**
     * The Postgres database port.
     */
    declare public readonly port: pulumi.Output<number | undefined>;
    /**
     * The fully qualified name of the connection.
     */
    declare public /*out*/ readonly qualifiedSqlName: pulumi.Output<string>;
    /**
     * The region to use for the resource connection. If not set, the default region is used.
     */
    declare public readonly region: pulumi.Output<string>;
    /**
     * The identifier for the connection schema in Materialize. Defaults to <span pulumi-lang-nodejs="`public`" pulumi-lang-dotnet="`Public`" pulumi-lang-go="`public`" pulumi-lang-python="`public`" pulumi-lang-yaml="`public`" pulumi-lang-java="`public`">`public`</span>.
     */
    declare public readonly schemaName: pulumi.Output<string | undefined>;
    /**
     * The SSH tunnel configuration for the Postgres database.
     */
    declare public readonly sshTunnel: pulumi.Output<outputs.ConnectionPostgresSshTunnel | undefined>;
    /**
     * The client certificate for the Postgres database.. Can be supplied as either free text using <span pulumi-lang-nodejs="`text`" pulumi-lang-dotnet="`Text`" pulumi-lang-go="`text`" pulumi-lang-python="`text`" pulumi-lang-yaml="`text`" pulumi-lang-java="`text`">`text`</span> or reference to a secret object using <span pulumi-lang-nodejs="`secret`" pulumi-lang-dotnet="`Secret`" pulumi-lang-go="`secret`" pulumi-lang-python="`secret`" pulumi-lang-yaml="`secret`" pulumi-lang-java="`secret`">`secret`</span>.
     */
    declare public readonly sslCertificate: pulumi.Output<outputs.ConnectionPostgresSslCertificate | undefined>;
    /**
     * The CA certificate for the Postgres database.. Can be supplied as either free text using <span pulumi-lang-nodejs="`text`" pulumi-lang-dotnet="`Text`" pulumi-lang-go="`text`" pulumi-lang-python="`text`" pulumi-lang-yaml="`text`" pulumi-lang-java="`text`">`text`</span> or reference to a secret object using <span pulumi-lang-nodejs="`secret`" pulumi-lang-dotnet="`Secret`" pulumi-lang-go="`secret`" pulumi-lang-python="`secret`" pulumi-lang-yaml="`secret`" pulumi-lang-java="`secret`">`secret`</span>.
     */
    declare public readonly sslCertificateAuthority: pulumi.Output<outputs.ConnectionPostgresSslCertificateAuthority | undefined>;
    /**
     * The client key for the Postgres database.
     */
    declare public readonly sslKey: pulumi.Output<outputs.ConnectionPostgresSslKey | undefined>;
    /**
     * The SSL mode for the Postgres database.
     */
    declare public readonly sslMode: pulumi.Output<string | undefined>;
    /**
     * The Postgres database username.. Can be supplied as either free text using <span pulumi-lang-nodejs="`text`" pulumi-lang-dotnet="`Text`" pulumi-lang-go="`text`" pulumi-lang-python="`text`" pulumi-lang-yaml="`text`" pulumi-lang-java="`text`">`text`</span> or reference to a secret object using <span pulumi-lang-nodejs="`secret`" pulumi-lang-dotnet="`Secret`" pulumi-lang-go="`secret`" pulumi-lang-python="`secret`" pulumi-lang-yaml="`secret`" pulumi-lang-java="`secret`">`secret`</span>.
     */
    declare public readonly user: pulumi.Output<outputs.ConnectionPostgresUser>;
    /**
     * If the connection should wait for validation.
     */
    declare public readonly validate: pulumi.Output<boolean | undefined>;

    /**
     * Create a ConnectionPostgres resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ConnectionPostgresArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ConnectionPostgresArgs | ConnectionPostgresState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ConnectionPostgresState | undefined;
            resourceInputs["awsPrivatelink"] = state?.awsPrivatelink;
            resourceInputs["comment"] = state?.comment;
            resourceInputs["connectionPostgresId"] = state?.connectionPostgresId;
            resourceInputs["database"] = state?.database;
            resourceInputs["databaseName"] = state?.databaseName;
            resourceInputs["host"] = state?.host;
            resourceInputs["name"] = state?.name;
            resourceInputs["ownershipRole"] = state?.ownershipRole;
            resourceInputs["password"] = state?.password;
            resourceInputs["port"] = state?.port;
            resourceInputs["qualifiedSqlName"] = state?.qualifiedSqlName;
            resourceInputs["region"] = state?.region;
            resourceInputs["schemaName"] = state?.schemaName;
            resourceInputs["sshTunnel"] = state?.sshTunnel;
            resourceInputs["sslCertificate"] = state?.sslCertificate;
            resourceInputs["sslCertificateAuthority"] = state?.sslCertificateAuthority;
            resourceInputs["sslKey"] = state?.sslKey;
            resourceInputs["sslMode"] = state?.sslMode;
            resourceInputs["user"] = state?.user;
            resourceInputs["validate"] = state?.validate;
        } else {
            const args = argsOrState as ConnectionPostgresArgs | undefined;
            if (args?.database === undefined && !opts.urn) {
                throw new Error("Missing required property 'database'");
            }
            if (args?.host === undefined && !opts.urn) {
                throw new Error("Missing required property 'host'");
            }
            if (args?.user === undefined && !opts.urn) {
                throw new Error("Missing required property 'user'");
            }
            resourceInputs["awsPrivatelink"] = args?.awsPrivatelink;
            resourceInputs["comment"] = args?.comment;
            resourceInputs["connectionPostgresId"] = args?.connectionPostgresId;
            resourceInputs["database"] = args?.database;
            resourceInputs["databaseName"] = args?.databaseName;
            resourceInputs["host"] = args?.host;
            resourceInputs["name"] = args?.name;
            resourceInputs["ownershipRole"] = args?.ownershipRole;
            resourceInputs["password"] = args?.password;
            resourceInputs["port"] = args?.port;
            resourceInputs["region"] = args?.region;
            resourceInputs["schemaName"] = args?.schemaName;
            resourceInputs["sshTunnel"] = args?.sshTunnel;
            resourceInputs["sslCertificate"] = args?.sslCertificate;
            resourceInputs["sslCertificateAuthority"] = args?.sslCertificateAuthority;
            resourceInputs["sslKey"] = args?.sslKey;
            resourceInputs["sslMode"] = args?.sslMode;
            resourceInputs["user"] = args?.user;
            resourceInputs["validate"] = args?.validate;
            resourceInputs["qualifiedSqlName"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ConnectionPostgres.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering ConnectionPostgres resources.
 */
export interface ConnectionPostgresState {
    /**
     * The AWS PrivateLink configuration for the Postgres database.
     */
    awsPrivatelink?: pulumi.Input<inputs.ConnectionPostgresAwsPrivatelink>;
    /**
     * Comment on an object in the database.
     */
    comment?: pulumi.Input<string>;
    connectionPostgresId?: pulumi.Input<string>;
    /**
     * The target Postgres database.
     */
    database?: pulumi.Input<string>;
    /**
     * The identifier for the connection database in Materialize. Defaults to `MZ_DATABASE` environment variable if set or <span pulumi-lang-nodejs="`materialize`" pulumi-lang-dotnet="`Materialize`" pulumi-lang-go="`materialize`" pulumi-lang-python="`materialize`" pulumi-lang-yaml="`materialize`" pulumi-lang-java="`materialize`">`materialize`</span> if environment variable is not set.
     */
    databaseName?: pulumi.Input<string>;
    /**
     * The Postgres database hostname.
     */
    host?: pulumi.Input<string>;
    /**
     * The identifier for the connection.
     */
    name?: pulumi.Input<string>;
    /**
     * The owernship role of the object.
     */
    ownershipRole?: pulumi.Input<string>;
    /**
     * The Postgres database password.
     */
    password?: pulumi.Input<inputs.ConnectionPostgresPassword>;
    /**
     * The Postgres database port.
     */
    port?: pulumi.Input<number>;
    /**
     * The fully qualified name of the connection.
     */
    qualifiedSqlName?: pulumi.Input<string>;
    /**
     * The region to use for the resource connection. If not set, the default region is used.
     */
    region?: pulumi.Input<string>;
    /**
     * The identifier for the connection schema in Materialize. Defaults to <span pulumi-lang-nodejs="`public`" pulumi-lang-dotnet="`Public`" pulumi-lang-go="`public`" pulumi-lang-python="`public`" pulumi-lang-yaml="`public`" pulumi-lang-java="`public`">`public`</span>.
     */
    schemaName?: pulumi.Input<string>;
    /**
     * The SSH tunnel configuration for the Postgres database.
     */
    sshTunnel?: pulumi.Input<inputs.ConnectionPostgresSshTunnel>;
    /**
     * The client certificate for the Postgres database.. Can be supplied as either free text using <span pulumi-lang-nodejs="`text`" pulumi-lang-dotnet="`Text`" pulumi-lang-go="`text`" pulumi-lang-python="`text`" pulumi-lang-yaml="`text`" pulumi-lang-java="`text`">`text`</span> or reference to a secret object using <span pulumi-lang-nodejs="`secret`" pulumi-lang-dotnet="`Secret`" pulumi-lang-go="`secret`" pulumi-lang-python="`secret`" pulumi-lang-yaml="`secret`" pulumi-lang-java="`secret`">`secret`</span>.
     */
    sslCertificate?: pulumi.Input<inputs.ConnectionPostgresSslCertificate>;
    /**
     * The CA certificate for the Postgres database.. Can be supplied as either free text using <span pulumi-lang-nodejs="`text`" pulumi-lang-dotnet="`Text`" pulumi-lang-go="`text`" pulumi-lang-python="`text`" pulumi-lang-yaml="`text`" pulumi-lang-java="`text`">`text`</span> or reference to a secret object using <span pulumi-lang-nodejs="`secret`" pulumi-lang-dotnet="`Secret`" pulumi-lang-go="`secret`" pulumi-lang-python="`secret`" pulumi-lang-yaml="`secret`" pulumi-lang-java="`secret`">`secret`</span>.
     */
    sslCertificateAuthority?: pulumi.Input<inputs.ConnectionPostgresSslCertificateAuthority>;
    /**
     * The client key for the Postgres database.
     */
    sslKey?: pulumi.Input<inputs.ConnectionPostgresSslKey>;
    /**
     * The SSL mode for the Postgres database.
     */
    sslMode?: pulumi.Input<string>;
    /**
     * The Postgres database username.. Can be supplied as either free text using <span pulumi-lang-nodejs="`text`" pulumi-lang-dotnet="`Text`" pulumi-lang-go="`text`" pulumi-lang-python="`text`" pulumi-lang-yaml="`text`" pulumi-lang-java="`text`">`text`</span> or reference to a secret object using <span pulumi-lang-nodejs="`secret`" pulumi-lang-dotnet="`Secret`" pulumi-lang-go="`secret`" pulumi-lang-python="`secret`" pulumi-lang-yaml="`secret`" pulumi-lang-java="`secret`">`secret`</span>.
     */
    user?: pulumi.Input<inputs.ConnectionPostgresUser>;
    /**
     * If the connection should wait for validation.
     */
    validate?: pulumi.Input<boolean>;
}

/**
 * The set of arguments for constructing a ConnectionPostgres resource.
 */
export interface ConnectionPostgresArgs {
    /**
     * The AWS PrivateLink configuration for the Postgres database.
     */
    awsPrivatelink?: pulumi.Input<inputs.ConnectionPostgresAwsPrivatelink>;
    /**
     * Comment on an object in the database.
     */
    comment?: pulumi.Input<string>;
    connectionPostgresId?: pulumi.Input<string>;
    /**
     * The target Postgres database.
     */
    database: pulumi.Input<string>;
    /**
     * The identifier for the connection database in Materialize. Defaults to `MZ_DATABASE` environment variable if set or <span pulumi-lang-nodejs="`materialize`" pulumi-lang-dotnet="`Materialize`" pulumi-lang-go="`materialize`" pulumi-lang-python="`materialize`" pulumi-lang-yaml="`materialize`" pulumi-lang-java="`materialize`">`materialize`</span> if environment variable is not set.
     */
    databaseName?: pulumi.Input<string>;
    /**
     * The Postgres database hostname.
     */
    host: pulumi.Input<string>;
    /**
     * The identifier for the connection.
     */
    name?: pulumi.Input<string>;
    /**
     * The owernship role of the object.
     */
    ownershipRole?: pulumi.Input<string>;
    /**
     * The Postgres database password.
     */
    password?: pulumi.Input<inputs.ConnectionPostgresPassword>;
    /**
     * The Postgres database port.
     */
    port?: pulumi.Input<number>;
    /**
     * The region to use for the resource connection. If not set, the default region is used.
     */
    region?: pulumi.Input<string>;
    /**
     * The identifier for the connection schema in Materialize. Defaults to <span pulumi-lang-nodejs="`public`" pulumi-lang-dotnet="`Public`" pulumi-lang-go="`public`" pulumi-lang-python="`public`" pulumi-lang-yaml="`public`" pulumi-lang-java="`public`">`public`</span>.
     */
    schemaName?: pulumi.Input<string>;
    /**
     * The SSH tunnel configuration for the Postgres database.
     */
    sshTunnel?: pulumi.Input<inputs.ConnectionPostgresSshTunnel>;
    /**
     * The client certificate for the Postgres database.. Can be supplied as either free text using <span pulumi-lang-nodejs="`text`" pulumi-lang-dotnet="`Text`" pulumi-lang-go="`text`" pulumi-lang-python="`text`" pulumi-lang-yaml="`text`" pulumi-lang-java="`text`">`text`</span> or reference to a secret object using <span pulumi-lang-nodejs="`secret`" pulumi-lang-dotnet="`Secret`" pulumi-lang-go="`secret`" pulumi-lang-python="`secret`" pulumi-lang-yaml="`secret`" pulumi-lang-java="`secret`">`secret`</span>.
     */
    sslCertificate?: pulumi.Input<inputs.ConnectionPostgresSslCertificate>;
    /**
     * The CA certificate for the Postgres database.. Can be supplied as either free text using <span pulumi-lang-nodejs="`text`" pulumi-lang-dotnet="`Text`" pulumi-lang-go="`text`" pulumi-lang-python="`text`" pulumi-lang-yaml="`text`" pulumi-lang-java="`text`">`text`</span> or reference to a secret object using <span pulumi-lang-nodejs="`secret`" pulumi-lang-dotnet="`Secret`" pulumi-lang-go="`secret`" pulumi-lang-python="`secret`" pulumi-lang-yaml="`secret`" pulumi-lang-java="`secret`">`secret`</span>.
     */
    sslCertificateAuthority?: pulumi.Input<inputs.ConnectionPostgresSslCertificateAuthority>;
    /**
     * The client key for the Postgres database.
     */
    sslKey?: pulumi.Input<inputs.ConnectionPostgresSslKey>;
    /**
     * The SSL mode for the Postgres database.
     */
    sslMode?: pulumi.Input<string>;
    /**
     * The Postgres database username.. Can be supplied as either free text using <span pulumi-lang-nodejs="`text`" pulumi-lang-dotnet="`Text`" pulumi-lang-go="`text`" pulumi-lang-python="`text`" pulumi-lang-yaml="`text`" pulumi-lang-java="`text`">`text`</span> or reference to a secret object using <span pulumi-lang-nodejs="`secret`" pulumi-lang-dotnet="`Secret`" pulumi-lang-go="`secret`" pulumi-lang-python="`secret`" pulumi-lang-yaml="`secret`" pulumi-lang-java="`secret`">`secret`</span>.
     */
    user: pulumi.Input<inputs.ConnectionPostgresUser>;
    /**
     * If the connection should wait for validation.
     */
    validate?: pulumi.Input<boolean>;
}
