// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class DatabaseGrant extends pulumi.CustomResource {
    /**
     * Get an existing DatabaseGrant resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: DatabaseGrantState, opts?: pulumi.CustomResourceOptions): DatabaseGrant {
        return new DatabaseGrant(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'materialize:index/databaseGrant:DatabaseGrant';

    /**
     * Returns true if the given object is an instance of DatabaseGrant.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is DatabaseGrant {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === DatabaseGrant.__pulumiType;
    }

    declare public readonly databaseGrantId: pulumi.Output<string>;
    /**
     * The database that is being granted on.
     */
    declare public readonly databaseName: pulumi.Output<string>;
    /**
     * The privilege to grant to the object.
     */
    declare public readonly privilege: pulumi.Output<string>;
    /**
     * The region to use for the resource connection. If not set, the default region is used.
     */
    declare public readonly region: pulumi.Output<string>;
    /**
     * The name of the role to grant privilege to.
     */
    declare public readonly roleName: pulumi.Output<string>;

    /**
     * Create a DatabaseGrant resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: DatabaseGrantArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: DatabaseGrantArgs | DatabaseGrantState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as DatabaseGrantState | undefined;
            resourceInputs["databaseGrantId"] = state?.databaseGrantId;
            resourceInputs["databaseName"] = state?.databaseName;
            resourceInputs["privilege"] = state?.privilege;
            resourceInputs["region"] = state?.region;
            resourceInputs["roleName"] = state?.roleName;
        } else {
            const args = argsOrState as DatabaseGrantArgs | undefined;
            if (args?.databaseName === undefined && !opts.urn) {
                throw new Error("Missing required property 'databaseName'");
            }
            if (args?.privilege === undefined && !opts.urn) {
                throw new Error("Missing required property 'privilege'");
            }
            if (args?.roleName === undefined && !opts.urn) {
                throw new Error("Missing required property 'roleName'");
            }
            resourceInputs["databaseGrantId"] = args?.databaseGrantId;
            resourceInputs["databaseName"] = args?.databaseName;
            resourceInputs["privilege"] = args?.privilege;
            resourceInputs["region"] = args?.region;
            resourceInputs["roleName"] = args?.roleName;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(DatabaseGrant.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering DatabaseGrant resources.
 */
export interface DatabaseGrantState {
    databaseGrantId?: pulumi.Input<string>;
    /**
     * The database that is being granted on.
     */
    databaseName?: pulumi.Input<string>;
    /**
     * The privilege to grant to the object.
     */
    privilege?: pulumi.Input<string>;
    /**
     * The region to use for the resource connection. If not set, the default region is used.
     */
    region?: pulumi.Input<string>;
    /**
     * The name of the role to grant privilege to.
     */
    roleName?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a DatabaseGrant resource.
 */
export interface DatabaseGrantArgs {
    databaseGrantId?: pulumi.Input<string>;
    /**
     * The database that is being granted on.
     */
    databaseName: pulumi.Input<string>;
    /**
     * The privilege to grant to the object.
     */
    privilege: pulumi.Input<string>;
    /**
     * The region to use for the resource connection. If not set, the default region is used.
     */
    region?: pulumi.Input<string>;
    /**
     * The name of the role to grant privilege to.
     */
    roleName: pulumi.Input<string>;
}
