// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getNetworkPolicy(args?: GetNetworkPolicyArgs, opts?: pulumi.InvokeOptions): Promise<GetNetworkPolicyResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("materialize:index/getNetworkPolicy:getNetworkPolicy", {
        "id": args.id,
        "region": args.region,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getNetworkPolicy.
 */
export interface GetNetworkPolicyArgs {
    id?: string;
    region?: string;
}

/**
 * A collection of values returned by getNetworkPolicy.
 */
export interface GetNetworkPolicyResult {
    readonly id: string;
    readonly networkPolicies: outputs.GetNetworkPolicyNetworkPolicy[];
    readonly region: string;
}
export function getNetworkPolicyOutput(args?: GetNetworkPolicyOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetNetworkPolicyResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("materialize:index/getNetworkPolicy:getNetworkPolicy", {
        "id": args.id,
        "region": args.region,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getNetworkPolicy.
 */
export interface GetNetworkPolicyOutputArgs {
    id?: pulumi.Input<string>;
    region?: pulumi.Input<string>;
}
