// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Index extends pulumi.CustomResource {
    /**
     * Get an existing Index resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: IndexState, opts?: pulumi.CustomResourceOptions): Index {
        return new Index(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'materialize:index/index:Index';

    /**
     * Returns true if the given object is an instance of Index.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Index {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Index.__pulumiType;
    }

    /**
     * The cluster to maintain this index.
     */
    declare public readonly clusterName: pulumi.Output<string>;
    /**
     * The expressions to use as the key for the index.
     */
    declare public readonly colExprs: pulumi.Output<outputs.IndexColExpr[] | undefined>;
    /**
     * Comment on an object in the database.
     */
    declare public readonly comment: pulumi.Output<string | undefined>;
    /**
     * The identifier for the index database.
     */
    declare public /*out*/ readonly databaseName: pulumi.Output<string>;
    /**
     * Creates a default index using all inferred columns are used. Required if<span pulumi-lang-nodejs=" colExpr " pulumi-lang-dotnet=" ColExpr " pulumi-lang-go=" colExpr " pulumi-lang-python=" col_expr " pulumi-lang-yaml=" colExpr " pulumi-lang-java=" colExpr "> col_expr </span>is not set.
     */
    declare public readonly default: pulumi.Output<boolean | undefined>;
    declare public readonly indexId: pulumi.Output<string>;
    /**
     * The name of the index method to use.
     */
    declare public readonly method: pulumi.Output<string | undefined>;
    /**
     * The identifier for the index.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The name of the source, view, or materialized view on which you want to create an index.
     */
    declare public readonly objName: pulumi.Output<outputs.IndexObjName>;
    /**
     * The fully qualified name of the index.
     */
    declare public /*out*/ readonly qualifiedSqlName: pulumi.Output<string>;
    /**
     * The region to use for the resource connection. If not set, the default region is used.
     */
    declare public readonly region: pulumi.Output<string>;
    /**
     * The identifier for the index schema.
     */
    declare public /*out*/ readonly schemaName: pulumi.Output<string>;

    /**
     * Create a Index resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: IndexArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: IndexArgs | IndexState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as IndexState | undefined;
            resourceInputs["clusterName"] = state?.clusterName;
            resourceInputs["colExprs"] = state?.colExprs;
            resourceInputs["comment"] = state?.comment;
            resourceInputs["databaseName"] = state?.databaseName;
            resourceInputs["default"] = state?.default;
            resourceInputs["indexId"] = state?.indexId;
            resourceInputs["method"] = state?.method;
            resourceInputs["name"] = state?.name;
            resourceInputs["objName"] = state?.objName;
            resourceInputs["qualifiedSqlName"] = state?.qualifiedSqlName;
            resourceInputs["region"] = state?.region;
            resourceInputs["schemaName"] = state?.schemaName;
        } else {
            const args = argsOrState as IndexArgs | undefined;
            if (args?.clusterName === undefined && !opts.urn) {
                throw new Error("Missing required property 'clusterName'");
            }
            if (args?.objName === undefined && !opts.urn) {
                throw new Error("Missing required property 'objName'");
            }
            resourceInputs["clusterName"] = args?.clusterName;
            resourceInputs["colExprs"] = args?.colExprs;
            resourceInputs["comment"] = args?.comment;
            resourceInputs["default"] = args?.default;
            resourceInputs["indexId"] = args?.indexId;
            resourceInputs["method"] = args?.method;
            resourceInputs["name"] = args?.name;
            resourceInputs["objName"] = args?.objName;
            resourceInputs["region"] = args?.region;
            resourceInputs["databaseName"] = undefined /*out*/;
            resourceInputs["qualifiedSqlName"] = undefined /*out*/;
            resourceInputs["schemaName"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Index.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Index resources.
 */
export interface IndexState {
    /**
     * The cluster to maintain this index.
     */
    clusterName?: pulumi.Input<string>;
    /**
     * The expressions to use as the key for the index.
     */
    colExprs?: pulumi.Input<pulumi.Input<inputs.IndexColExpr>[]>;
    /**
     * Comment on an object in the database.
     */
    comment?: pulumi.Input<string>;
    /**
     * The identifier for the index database.
     */
    databaseName?: pulumi.Input<string>;
    /**
     * Creates a default index using all inferred columns are used. Required if<span pulumi-lang-nodejs=" colExpr " pulumi-lang-dotnet=" ColExpr " pulumi-lang-go=" colExpr " pulumi-lang-python=" col_expr " pulumi-lang-yaml=" colExpr " pulumi-lang-java=" colExpr "> col_expr </span>is not set.
     */
    default?: pulumi.Input<boolean>;
    indexId?: pulumi.Input<string>;
    /**
     * The name of the index method to use.
     */
    method?: pulumi.Input<string>;
    /**
     * The identifier for the index.
     */
    name?: pulumi.Input<string>;
    /**
     * The name of the source, view, or materialized view on which you want to create an index.
     */
    objName?: pulumi.Input<inputs.IndexObjName>;
    /**
     * The fully qualified name of the index.
     */
    qualifiedSqlName?: pulumi.Input<string>;
    /**
     * The region to use for the resource connection. If not set, the default region is used.
     */
    region?: pulumi.Input<string>;
    /**
     * The identifier for the index schema.
     */
    schemaName?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Index resource.
 */
export interface IndexArgs {
    /**
     * The cluster to maintain this index.
     */
    clusterName: pulumi.Input<string>;
    /**
     * The expressions to use as the key for the index.
     */
    colExprs?: pulumi.Input<pulumi.Input<inputs.IndexColExpr>[]>;
    /**
     * Comment on an object in the database.
     */
    comment?: pulumi.Input<string>;
    /**
     * Creates a default index using all inferred columns are used. Required if<span pulumi-lang-nodejs=" colExpr " pulumi-lang-dotnet=" ColExpr " pulumi-lang-go=" colExpr " pulumi-lang-python=" col_expr " pulumi-lang-yaml=" colExpr " pulumi-lang-java=" colExpr "> col_expr </span>is not set.
     */
    default?: pulumi.Input<boolean>;
    indexId?: pulumi.Input<string>;
    /**
     * The name of the index method to use.
     */
    method?: pulumi.Input<string>;
    /**
     * The identifier for the index.
     */
    name?: pulumi.Input<string>;
    /**
     * The name of the source, view, or materialized view on which you want to create an index.
     */
    objName: pulumi.Input<inputs.IndexObjName>;
    /**
     * The region to use for the resource connection. If not set, the default region is used.
     */
    region?: pulumi.Input<string>;
}
