// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class MaterializedView extends pulumi.CustomResource {
    /**
     * Get an existing MaterializedView resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: MaterializedViewState, opts?: pulumi.CustomResourceOptions): MaterializedView {
        return new MaterializedView(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'materialize:index/materializedView:MaterializedView';

    /**
     * Returns true if the given object is an instance of MaterializedView.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is MaterializedView {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === MaterializedView.__pulumiType;
    }

    /**
     * The cluster to maintain the materialized view.
     */
    declare public readonly clusterName: pulumi.Output<string>;
    /**
     * Comment on an object in the database.
     */
    declare public readonly comment: pulumi.Output<string | undefined>;
    /**
     * The SQL statement used to create the materialized view.
     */
    declare public /*out*/ readonly createSql: pulumi.Output<string>;
    /**
     * The identifier for the materialized view database in Materialize. Defaults to `MZ_DATABASE` environment variable if set or <span pulumi-lang-nodejs="`materialize`" pulumi-lang-dotnet="`Materialize`" pulumi-lang-go="`materialize`" pulumi-lang-python="`materialize`" pulumi-lang-yaml="`materialize`" pulumi-lang-java="`materialize`">`materialize`</span> if environment variable is not set.
     */
    declare public readonly databaseName: pulumi.Output<string | undefined>;
    declare public readonly materializedViewId: pulumi.Output<string>;
    /**
     * The identifier for the materialized view.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * A list of columns for which to create non-null assertions.
     */
    declare public readonly notNullAssertions: pulumi.Output<string[] | undefined>;
    /**
     * The owernship role of the object.
     */
    declare public readonly ownershipRole: pulumi.Output<string>;
    /**
     * The fully qualified name of the materialized view.
     */
    declare public /*out*/ readonly qualifiedSqlName: pulumi.Output<string>;
    /**
     * The region to use for the resource connection. If not set, the default region is used.
     */
    declare public readonly region: pulumi.Output<string>;
    /**
     * The identifier for the materialized view schema in Materialize. Defaults to <span pulumi-lang-nodejs="`public`" pulumi-lang-dotnet="`Public`" pulumi-lang-go="`public`" pulumi-lang-python="`public`" pulumi-lang-yaml="`public`" pulumi-lang-java="`public`">`public`</span>.
     */
    declare public readonly schemaName: pulumi.Output<string | undefined>;
    /**
     * The SQL statement for the materialized view.
     */
    declare public readonly statement: pulumi.Output<string>;

    /**
     * Create a MaterializedView resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: MaterializedViewArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: MaterializedViewArgs | MaterializedViewState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as MaterializedViewState | undefined;
            resourceInputs["clusterName"] = state?.clusterName;
            resourceInputs["comment"] = state?.comment;
            resourceInputs["createSql"] = state?.createSql;
            resourceInputs["databaseName"] = state?.databaseName;
            resourceInputs["materializedViewId"] = state?.materializedViewId;
            resourceInputs["name"] = state?.name;
            resourceInputs["notNullAssertions"] = state?.notNullAssertions;
            resourceInputs["ownershipRole"] = state?.ownershipRole;
            resourceInputs["qualifiedSqlName"] = state?.qualifiedSqlName;
            resourceInputs["region"] = state?.region;
            resourceInputs["schemaName"] = state?.schemaName;
            resourceInputs["statement"] = state?.statement;
        } else {
            const args = argsOrState as MaterializedViewArgs | undefined;
            if (args?.clusterName === undefined && !opts.urn) {
                throw new Error("Missing required property 'clusterName'");
            }
            if (args?.statement === undefined && !opts.urn) {
                throw new Error("Missing required property 'statement'");
            }
            resourceInputs["clusterName"] = args?.clusterName;
            resourceInputs["comment"] = args?.comment;
            resourceInputs["databaseName"] = args?.databaseName;
            resourceInputs["materializedViewId"] = args?.materializedViewId;
            resourceInputs["name"] = args?.name;
            resourceInputs["notNullAssertions"] = args?.notNullAssertions;
            resourceInputs["ownershipRole"] = args?.ownershipRole;
            resourceInputs["region"] = args?.region;
            resourceInputs["schemaName"] = args?.schemaName;
            resourceInputs["statement"] = args?.statement;
            resourceInputs["createSql"] = undefined /*out*/;
            resourceInputs["qualifiedSqlName"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(MaterializedView.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering MaterializedView resources.
 */
export interface MaterializedViewState {
    /**
     * The cluster to maintain the materialized view.
     */
    clusterName?: pulumi.Input<string>;
    /**
     * Comment on an object in the database.
     */
    comment?: pulumi.Input<string>;
    /**
     * The SQL statement used to create the materialized view.
     */
    createSql?: pulumi.Input<string>;
    /**
     * The identifier for the materialized view database in Materialize. Defaults to `MZ_DATABASE` environment variable if set or <span pulumi-lang-nodejs="`materialize`" pulumi-lang-dotnet="`Materialize`" pulumi-lang-go="`materialize`" pulumi-lang-python="`materialize`" pulumi-lang-yaml="`materialize`" pulumi-lang-java="`materialize`">`materialize`</span> if environment variable is not set.
     */
    databaseName?: pulumi.Input<string>;
    materializedViewId?: pulumi.Input<string>;
    /**
     * The identifier for the materialized view.
     */
    name?: pulumi.Input<string>;
    /**
     * A list of columns for which to create non-null assertions.
     */
    notNullAssertions?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The owernship role of the object.
     */
    ownershipRole?: pulumi.Input<string>;
    /**
     * The fully qualified name of the materialized view.
     */
    qualifiedSqlName?: pulumi.Input<string>;
    /**
     * The region to use for the resource connection. If not set, the default region is used.
     */
    region?: pulumi.Input<string>;
    /**
     * The identifier for the materialized view schema in Materialize. Defaults to <span pulumi-lang-nodejs="`public`" pulumi-lang-dotnet="`Public`" pulumi-lang-go="`public`" pulumi-lang-python="`public`" pulumi-lang-yaml="`public`" pulumi-lang-java="`public`">`public`</span>.
     */
    schemaName?: pulumi.Input<string>;
    /**
     * The SQL statement for the materialized view.
     */
    statement?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a MaterializedView resource.
 */
export interface MaterializedViewArgs {
    /**
     * The cluster to maintain the materialized view.
     */
    clusterName: pulumi.Input<string>;
    /**
     * Comment on an object in the database.
     */
    comment?: pulumi.Input<string>;
    /**
     * The identifier for the materialized view database in Materialize. Defaults to `MZ_DATABASE` environment variable if set or <span pulumi-lang-nodejs="`materialize`" pulumi-lang-dotnet="`Materialize`" pulumi-lang-go="`materialize`" pulumi-lang-python="`materialize`" pulumi-lang-yaml="`materialize`" pulumi-lang-java="`materialize`">`materialize`</span> if environment variable is not set.
     */
    databaseName?: pulumi.Input<string>;
    materializedViewId?: pulumi.Input<string>;
    /**
     * The identifier for the materialized view.
     */
    name?: pulumi.Input<string>;
    /**
     * A list of columns for which to create non-null assertions.
     */
    notNullAssertions?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The owernship role of the object.
     */
    ownershipRole?: pulumi.Input<string>;
    /**
     * The region to use for the resource connection. If not set, the default region is used.
     */
    region?: pulumi.Input<string>;
    /**
     * The identifier for the materialized view schema in Materialize. Defaults to <span pulumi-lang-nodejs="`public`" pulumi-lang-dotnet="`Public`" pulumi-lang-go="`public`" pulumi-lang-python="`public`" pulumi-lang-yaml="`public`" pulumi-lang-java="`public`">`public`</span>.
     */
    schemaName?: pulumi.Input<string>;
    /**
     * The SQL statement for the materialized view.
     */
    statement: pulumi.Input<string>;
}
