// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class MaterializedViewGrant extends pulumi.CustomResource {
    /**
     * Get an existing MaterializedViewGrant resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: MaterializedViewGrantState, opts?: pulumi.CustomResourceOptions): MaterializedViewGrant {
        return new MaterializedViewGrant(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'materialize:index/materializedViewGrant:MaterializedViewGrant';

    /**
     * Returns true if the given object is an instance of MaterializedViewGrant.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is MaterializedViewGrant {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === MaterializedViewGrant.__pulumiType;
    }

    /**
     * The database that the materialized view belongs to.
     */
    declare public readonly databaseName: pulumi.Output<string>;
    declare public readonly materializedViewGrantId: pulumi.Output<string>;
    /**
     * The materialized view that is being granted on.
     */
    declare public readonly materializedViewName: pulumi.Output<string>;
    /**
     * The privilege to grant to the object.
     */
    declare public readonly privilege: pulumi.Output<string>;
    /**
     * The region to use for the resource connection. If not set, the default region is used.
     */
    declare public readonly region: pulumi.Output<string>;
    /**
     * The name of the role to grant privilege to.
     */
    declare public readonly roleName: pulumi.Output<string>;
    /**
     * The schema that the materialized view being to.
     */
    declare public readonly schemaName: pulumi.Output<string>;

    /**
     * Create a MaterializedViewGrant resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: MaterializedViewGrantArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: MaterializedViewGrantArgs | MaterializedViewGrantState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as MaterializedViewGrantState | undefined;
            resourceInputs["databaseName"] = state?.databaseName;
            resourceInputs["materializedViewGrantId"] = state?.materializedViewGrantId;
            resourceInputs["materializedViewName"] = state?.materializedViewName;
            resourceInputs["privilege"] = state?.privilege;
            resourceInputs["region"] = state?.region;
            resourceInputs["roleName"] = state?.roleName;
            resourceInputs["schemaName"] = state?.schemaName;
        } else {
            const args = argsOrState as MaterializedViewGrantArgs | undefined;
            if (args?.databaseName === undefined && !opts.urn) {
                throw new Error("Missing required property 'databaseName'");
            }
            if (args?.materializedViewName === undefined && !opts.urn) {
                throw new Error("Missing required property 'materializedViewName'");
            }
            if (args?.privilege === undefined && !opts.urn) {
                throw new Error("Missing required property 'privilege'");
            }
            if (args?.roleName === undefined && !opts.urn) {
                throw new Error("Missing required property 'roleName'");
            }
            if (args?.schemaName === undefined && !opts.urn) {
                throw new Error("Missing required property 'schemaName'");
            }
            resourceInputs["databaseName"] = args?.databaseName;
            resourceInputs["materializedViewGrantId"] = args?.materializedViewGrantId;
            resourceInputs["materializedViewName"] = args?.materializedViewName;
            resourceInputs["privilege"] = args?.privilege;
            resourceInputs["region"] = args?.region;
            resourceInputs["roleName"] = args?.roleName;
            resourceInputs["schemaName"] = args?.schemaName;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(MaterializedViewGrant.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering MaterializedViewGrant resources.
 */
export interface MaterializedViewGrantState {
    /**
     * The database that the materialized view belongs to.
     */
    databaseName?: pulumi.Input<string>;
    materializedViewGrantId?: pulumi.Input<string>;
    /**
     * The materialized view that is being granted on.
     */
    materializedViewName?: pulumi.Input<string>;
    /**
     * The privilege to grant to the object.
     */
    privilege?: pulumi.Input<string>;
    /**
     * The region to use for the resource connection. If not set, the default region is used.
     */
    region?: pulumi.Input<string>;
    /**
     * The name of the role to grant privilege to.
     */
    roleName?: pulumi.Input<string>;
    /**
     * The schema that the materialized view being to.
     */
    schemaName?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a MaterializedViewGrant resource.
 */
export interface MaterializedViewGrantArgs {
    /**
     * The database that the materialized view belongs to.
     */
    databaseName: pulumi.Input<string>;
    materializedViewGrantId?: pulumi.Input<string>;
    /**
     * The materialized view that is being granted on.
     */
    materializedViewName: pulumi.Input<string>;
    /**
     * The privilege to grant to the object.
     */
    privilege: pulumi.Input<string>;
    /**
     * The region to use for the resource connection. If not set, the default region is used.
     */
    region?: pulumi.Input<string>;
    /**
     * The name of the role to grant privilege to.
     */
    roleName: pulumi.Input<string>;
    /**
     * The schema that the materialized view being to.
     */
    schemaName: pulumi.Input<string>;
}
