// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Role extends pulumi.CustomResource {
    /**
     * Get an existing Role resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: RoleState, opts?: pulumi.CustomResourceOptions): Role {
        return new Role(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'materialize:index/role:Role';

    /**
     * Returns true if the given object is an instance of Role.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Role {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Role.__pulumiType;
    }

    /**
     * Comment on an object in the database.
     */
    declare public readonly comment: pulumi.Output<string | undefined>;
    /**
     * Grants the role the ability to inheritance of privileges of other roles. Unlike PostgreSQL, Materialize does not currently support `NOINHERIT`
     */
    declare public /*out*/ readonly inherit: pulumi.Output<boolean>;
    /**
     * Whether the role can log in. Only available in self-hosted Materialize environments with password authentication enabled. Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`">`false`</span>.
     */
    declare public readonly login: pulumi.Output<boolean | undefined>;
    /**
     * The identifier for the role.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Password for the role. Only available in self-hosted Materialize environments with password authentication enabled. Required for password-based authentication. Use<span pulumi-lang-nodejs=" passwordWo " pulumi-lang-dotnet=" PasswordWo " pulumi-lang-go=" passwordWo " pulumi-lang-python=" password_wo " pulumi-lang-yaml=" passwordWo " pulumi-lang-java=" passwordWo "> password_wo </span>for write-only ephemeral values that won't be stored in state.
     */
    declare public readonly password: pulumi.Output<string | undefined>;
    declare public readonly passwordWo: pulumi.Output<string | undefined>;
    /**
     * Version number for the write-only password. Increment this to trigger an update of the password value when using password_wo. Must be used with password_wo.
     */
    declare public readonly passwordWoVersion: pulumi.Output<number | undefined>;
    /**
     * The fully qualified name of the role.
     */
    declare public /*out*/ readonly qualifiedSqlName: pulumi.Output<string>;
    /**
     * The region to use for the resource connection. If not set, the default region is used.
     */
    declare public readonly region: pulumi.Output<string>;
    declare public readonly roleId: pulumi.Output<string>;
    /**
     * Whether the role is a superuser. Only available in self-hosted Materialize environments with password authentication enabled. Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`">`false`</span>.
     */
    declare public readonly superuser: pulumi.Output<boolean | undefined>;

    /**
     * Create a Role resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: RoleArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: RoleArgs | RoleState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as RoleState | undefined;
            resourceInputs["comment"] = state?.comment;
            resourceInputs["inherit"] = state?.inherit;
            resourceInputs["login"] = state?.login;
            resourceInputs["name"] = state?.name;
            resourceInputs["password"] = state?.password;
            resourceInputs["passwordWo"] = state?.passwordWo;
            resourceInputs["passwordWoVersion"] = state?.passwordWoVersion;
            resourceInputs["qualifiedSqlName"] = state?.qualifiedSqlName;
            resourceInputs["region"] = state?.region;
            resourceInputs["roleId"] = state?.roleId;
            resourceInputs["superuser"] = state?.superuser;
        } else {
            const args = argsOrState as RoleArgs | undefined;
            resourceInputs["comment"] = args?.comment;
            resourceInputs["login"] = args?.login;
            resourceInputs["name"] = args?.name;
            resourceInputs["password"] = args?.password ? pulumi.secret(args.password) : undefined;
            resourceInputs["passwordWo"] = args?.passwordWo ? pulumi.secret(args.passwordWo) : undefined;
            resourceInputs["passwordWoVersion"] = args?.passwordWoVersion;
            resourceInputs["region"] = args?.region;
            resourceInputs["roleId"] = args?.roleId;
            resourceInputs["superuser"] = args?.superuser;
            resourceInputs["inherit"] = undefined /*out*/;
            resourceInputs["qualifiedSqlName"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["password", "passwordWo"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Role.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Role resources.
 */
export interface RoleState {
    /**
     * Comment on an object in the database.
     */
    comment?: pulumi.Input<string>;
    /**
     * Grants the role the ability to inheritance of privileges of other roles. Unlike PostgreSQL, Materialize does not currently support `NOINHERIT`
     */
    inherit?: pulumi.Input<boolean>;
    /**
     * Whether the role can log in. Only available in self-hosted Materialize environments with password authentication enabled. Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`">`false`</span>.
     */
    login?: pulumi.Input<boolean>;
    /**
     * The identifier for the role.
     */
    name?: pulumi.Input<string>;
    /**
     * Password for the role. Only available in self-hosted Materialize environments with password authentication enabled. Required for password-based authentication. Use<span pulumi-lang-nodejs=" passwordWo " pulumi-lang-dotnet=" PasswordWo " pulumi-lang-go=" passwordWo " pulumi-lang-python=" password_wo " pulumi-lang-yaml=" passwordWo " pulumi-lang-java=" passwordWo "> password_wo </span>for write-only ephemeral values that won't be stored in state.
     */
    password?: pulumi.Input<string>;
    passwordWo?: pulumi.Input<string>;
    /**
     * Version number for the write-only password. Increment this to trigger an update of the password value when using password_wo. Must be used with password_wo.
     */
    passwordWoVersion?: pulumi.Input<number>;
    /**
     * The fully qualified name of the role.
     */
    qualifiedSqlName?: pulumi.Input<string>;
    /**
     * The region to use for the resource connection. If not set, the default region is used.
     */
    region?: pulumi.Input<string>;
    roleId?: pulumi.Input<string>;
    /**
     * Whether the role is a superuser. Only available in self-hosted Materialize environments with password authentication enabled. Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`">`false`</span>.
     */
    superuser?: pulumi.Input<boolean>;
}

/**
 * The set of arguments for constructing a Role resource.
 */
export interface RoleArgs {
    /**
     * Comment on an object in the database.
     */
    comment?: pulumi.Input<string>;
    /**
     * Whether the role can log in. Only available in self-hosted Materialize environments with password authentication enabled. Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`">`false`</span>.
     */
    login?: pulumi.Input<boolean>;
    /**
     * The identifier for the role.
     */
    name?: pulumi.Input<string>;
    /**
     * Password for the role. Only available in self-hosted Materialize environments with password authentication enabled. Required for password-based authentication. Use<span pulumi-lang-nodejs=" passwordWo " pulumi-lang-dotnet=" PasswordWo " pulumi-lang-go=" passwordWo " pulumi-lang-python=" password_wo " pulumi-lang-yaml=" passwordWo " pulumi-lang-java=" passwordWo "> password_wo </span>for write-only ephemeral values that won't be stored in state.
     */
    password?: pulumi.Input<string>;
    passwordWo?: pulumi.Input<string>;
    /**
     * Version number for the write-only password. Increment this to trigger an update of the password value when using password_wo. Must be used with password_wo.
     */
    passwordWoVersion?: pulumi.Input<number>;
    /**
     * The region to use for the resource connection. If not set, the default region is used.
     */
    region?: pulumi.Input<string>;
    roleId?: pulumi.Input<string>;
    /**
     * Whether the role is a superuser. Only available in self-hosted Materialize environments with password authentication enabled. Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`">`false`</span>.
     */
    superuser?: pulumi.Input<boolean>;
}
