// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class SecretGrant extends pulumi.CustomResource {
    /**
     * Get an existing SecretGrant resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SecretGrantState, opts?: pulumi.CustomResourceOptions): SecretGrant {
        return new SecretGrant(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'materialize:index/secretGrant:SecretGrant';

    /**
     * Returns true if the given object is an instance of SecretGrant.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SecretGrant {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SecretGrant.__pulumiType;
    }

    /**
     * The database that the secret belongs to.
     */
    declare public readonly databaseName: pulumi.Output<string>;
    /**
     * The privilege to grant to the object.
     */
    declare public readonly privilege: pulumi.Output<string>;
    /**
     * The region to use for the resource connection. If not set, the default region is used.
     */
    declare public readonly region: pulumi.Output<string>;
    /**
     * The name of the role to grant privilege to.
     */
    declare public readonly roleName: pulumi.Output<string>;
    /**
     * The schema that the secret being to.
     */
    declare public readonly schemaName: pulumi.Output<string>;
    declare public readonly secretGrantId: pulumi.Output<string>;
    /**
     * The secret that is being granted on.
     */
    declare public readonly secretName: pulumi.Output<string>;

    /**
     * Create a SecretGrant resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SecretGrantArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SecretGrantArgs | SecretGrantState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SecretGrantState | undefined;
            resourceInputs["databaseName"] = state?.databaseName;
            resourceInputs["privilege"] = state?.privilege;
            resourceInputs["region"] = state?.region;
            resourceInputs["roleName"] = state?.roleName;
            resourceInputs["schemaName"] = state?.schemaName;
            resourceInputs["secretGrantId"] = state?.secretGrantId;
            resourceInputs["secretName"] = state?.secretName;
        } else {
            const args = argsOrState as SecretGrantArgs | undefined;
            if (args?.databaseName === undefined && !opts.urn) {
                throw new Error("Missing required property 'databaseName'");
            }
            if (args?.privilege === undefined && !opts.urn) {
                throw new Error("Missing required property 'privilege'");
            }
            if (args?.roleName === undefined && !opts.urn) {
                throw new Error("Missing required property 'roleName'");
            }
            if (args?.schemaName === undefined && !opts.urn) {
                throw new Error("Missing required property 'schemaName'");
            }
            if (args?.secretName === undefined && !opts.urn) {
                throw new Error("Missing required property 'secretName'");
            }
            resourceInputs["databaseName"] = args?.databaseName;
            resourceInputs["privilege"] = args?.privilege;
            resourceInputs["region"] = args?.region;
            resourceInputs["roleName"] = args?.roleName;
            resourceInputs["schemaName"] = args?.schemaName;
            resourceInputs["secretGrantId"] = args?.secretGrantId;
            resourceInputs["secretName"] = args?.secretName;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(SecretGrant.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering SecretGrant resources.
 */
export interface SecretGrantState {
    /**
     * The database that the secret belongs to.
     */
    databaseName?: pulumi.Input<string>;
    /**
     * The privilege to grant to the object.
     */
    privilege?: pulumi.Input<string>;
    /**
     * The region to use for the resource connection. If not set, the default region is used.
     */
    region?: pulumi.Input<string>;
    /**
     * The name of the role to grant privilege to.
     */
    roleName?: pulumi.Input<string>;
    /**
     * The schema that the secret being to.
     */
    schemaName?: pulumi.Input<string>;
    secretGrantId?: pulumi.Input<string>;
    /**
     * The secret that is being granted on.
     */
    secretName?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a SecretGrant resource.
 */
export interface SecretGrantArgs {
    /**
     * The database that the secret belongs to.
     */
    databaseName: pulumi.Input<string>;
    /**
     * The privilege to grant to the object.
     */
    privilege: pulumi.Input<string>;
    /**
     * The region to use for the resource connection. If not set, the default region is used.
     */
    region?: pulumi.Input<string>;
    /**
     * The name of the role to grant privilege to.
     */
    roleName: pulumi.Input<string>;
    /**
     * The schema that the secret being to.
     */
    schemaName: pulumi.Input<string>;
    secretGrantId?: pulumi.Input<string>;
    /**
     * The secret that is being granted on.
     */
    secretName: pulumi.Input<string>;
}
