// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class SinkKafka extends pulumi.CustomResource {
    /**
     * Get an existing SinkKafka resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SinkKafkaState, opts?: pulumi.CustomResourceOptions): SinkKafka {
        return new SinkKafka(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'materialize:index/sinkKafka:SinkKafka';

    /**
     * Returns true if the given object is an instance of SinkKafka.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SinkKafka {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SinkKafka.__pulumiType;
    }

    /**
     * The cluster to maintain this sink.
     */
    declare public readonly clusterName: pulumi.Output<string>;
    /**
     * Comment on an object in the database.
     */
    declare public readonly comment: pulumi.Output<string | undefined>;
    /**
     * The type of compression to apply to messages before they are sent to Kafka.
     */
    declare public readonly compressionType: pulumi.Output<string | undefined>;
    /**
     * The identifier for the sink database in Materialize. Defaults to `MZ_DATABASE` environment variable if set or <span pulumi-lang-nodejs="`materialize`" pulumi-lang-dotnet="`Materialize`" pulumi-lang-go="`materialize`" pulumi-lang-python="`materialize`" pulumi-lang-yaml="`materialize`" pulumi-lang-java="`materialize`">`materialize`</span> if environment variable is not set.
     */
    declare public readonly databaseName: pulumi.Output<string | undefined>;
    /**
     * How to interpret records (e.g. Debezium, Upsert).
     */
    declare public readonly envelope: pulumi.Output<outputs.SinkKafkaEnvelope | undefined>;
    /**
     * How to decode raw bytes from different formats into data structures it can understand at runtime.
     */
    declare public readonly format: pulumi.Output<outputs.SinkKafkaFormat | undefined>;
    /**
     * The name of the source, table or materialized view you want to send to the sink.
     */
    declare public readonly from: pulumi.Output<outputs.SinkKafkaFrom>;
    /**
     * The name of a column containing additional headers to add to each message emitted by the sink. The column must be of type map[text => text] or map[text => bytea].
     */
    declare public readonly headers: pulumi.Output<string | undefined>;
    /**
     * The name of the Kafka connection to use in the sink.
     */
    declare public readonly kafkaConnection: pulumi.Output<outputs.SinkKafkaKafkaConnection>;
    /**
     * Disable Materialize's validation of the key's uniqueness.
     */
    declare public readonly keyNotEnforced: pulumi.Output<boolean | undefined>;
    /**
     * An optional list of columns to use for the Kafka key. If unspecified, the Kafka key is left unset.
     */
    declare public readonly keys: pulumi.Output<string[] | undefined>;
    /**
     * The identifier for the sink.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The owernship role of the object.
     */
    declare public readonly ownershipRole: pulumi.Output<string>;
    /**
     * A SQL expression used to partition the data in the Kafka sink. Can only be used with `ENVELOPE UPSERT`.
     */
    declare public readonly partitionBy: pulumi.Output<string | undefined>;
    /**
     * The fully qualified name of the sink.
     */
    declare public /*out*/ readonly qualifiedSqlName: pulumi.Output<string>;
    /**
     * The region to use for the resource connection. If not set, the default region is used.
     */
    declare public readonly region: pulumi.Output<string>;
    /**
     * The identifier for the sink schema in Materialize. Defaults to <span pulumi-lang-nodejs="`public`" pulumi-lang-dotnet="`Public`" pulumi-lang-go="`public`" pulumi-lang-python="`public`" pulumi-lang-yaml="`public`" pulumi-lang-java="`public`">`public`</span>.
     */
    declare public readonly schemaName: pulumi.Output<string | undefined>;
    declare public readonly sinkKafkaId: pulumi.Output<string>;
    /**
     * The size of the cluster maintaining this sink.
     */
    declare public /*out*/ readonly size: pulumi.Output<string>;
    /**
     * Whether to emit the consolidated results of the query before the sink was created at the start of the sink.
     */
    declare public readonly snapshot: pulumi.Output<boolean | undefined>;
    /**
     * The Kafka topic you want to subscribe to.
     */
    declare public readonly topic: pulumi.Output<string>;
    /**
     * Any topic-level configs to use when creating the Kafka topic (if the Kafka topic does not already exist).
     */
    declare public readonly topicConfig: pulumi.Output<{[key: string]: string} | undefined>;
    /**
     * The partition count to use when creating the Kafka topic (if the Kafka topic does not already exist).
     */
    declare public readonly topicPartitionCount: pulumi.Output<number | undefined>;
    /**
     * The replication factor to use when creating the Kafka topic (if the Kafka topic does not already exist).
     */
    declare public readonly topicReplicationFactor: pulumi.Output<number | undefined>;

    /**
     * Create a SinkKafka resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SinkKafkaArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SinkKafkaArgs | SinkKafkaState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SinkKafkaState | undefined;
            resourceInputs["clusterName"] = state?.clusterName;
            resourceInputs["comment"] = state?.comment;
            resourceInputs["compressionType"] = state?.compressionType;
            resourceInputs["databaseName"] = state?.databaseName;
            resourceInputs["envelope"] = state?.envelope;
            resourceInputs["format"] = state?.format;
            resourceInputs["from"] = state?.from;
            resourceInputs["headers"] = state?.headers;
            resourceInputs["kafkaConnection"] = state?.kafkaConnection;
            resourceInputs["keyNotEnforced"] = state?.keyNotEnforced;
            resourceInputs["keys"] = state?.keys;
            resourceInputs["name"] = state?.name;
            resourceInputs["ownershipRole"] = state?.ownershipRole;
            resourceInputs["partitionBy"] = state?.partitionBy;
            resourceInputs["qualifiedSqlName"] = state?.qualifiedSqlName;
            resourceInputs["region"] = state?.region;
            resourceInputs["schemaName"] = state?.schemaName;
            resourceInputs["sinkKafkaId"] = state?.sinkKafkaId;
            resourceInputs["size"] = state?.size;
            resourceInputs["snapshot"] = state?.snapshot;
            resourceInputs["topic"] = state?.topic;
            resourceInputs["topicConfig"] = state?.topicConfig;
            resourceInputs["topicPartitionCount"] = state?.topicPartitionCount;
            resourceInputs["topicReplicationFactor"] = state?.topicReplicationFactor;
        } else {
            const args = argsOrState as SinkKafkaArgs | undefined;
            if (args?.from === undefined && !opts.urn) {
                throw new Error("Missing required property 'from'");
            }
            if (args?.kafkaConnection === undefined && !opts.urn) {
                throw new Error("Missing required property 'kafkaConnection'");
            }
            if (args?.topic === undefined && !opts.urn) {
                throw new Error("Missing required property 'topic'");
            }
            resourceInputs["clusterName"] = args?.clusterName;
            resourceInputs["comment"] = args?.comment;
            resourceInputs["compressionType"] = args?.compressionType;
            resourceInputs["databaseName"] = args?.databaseName;
            resourceInputs["envelope"] = args?.envelope;
            resourceInputs["format"] = args?.format;
            resourceInputs["from"] = args?.from;
            resourceInputs["headers"] = args?.headers;
            resourceInputs["kafkaConnection"] = args?.kafkaConnection;
            resourceInputs["keyNotEnforced"] = args?.keyNotEnforced;
            resourceInputs["keys"] = args?.keys;
            resourceInputs["name"] = args?.name;
            resourceInputs["ownershipRole"] = args?.ownershipRole;
            resourceInputs["partitionBy"] = args?.partitionBy;
            resourceInputs["region"] = args?.region;
            resourceInputs["schemaName"] = args?.schemaName;
            resourceInputs["sinkKafkaId"] = args?.sinkKafkaId;
            resourceInputs["snapshot"] = args?.snapshot;
            resourceInputs["topic"] = args?.topic;
            resourceInputs["topicConfig"] = args?.topicConfig;
            resourceInputs["topicPartitionCount"] = args?.topicPartitionCount;
            resourceInputs["topicReplicationFactor"] = args?.topicReplicationFactor;
            resourceInputs["qualifiedSqlName"] = undefined /*out*/;
            resourceInputs["size"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(SinkKafka.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering SinkKafka resources.
 */
export interface SinkKafkaState {
    /**
     * The cluster to maintain this sink.
     */
    clusterName?: pulumi.Input<string>;
    /**
     * Comment on an object in the database.
     */
    comment?: pulumi.Input<string>;
    /**
     * The type of compression to apply to messages before they are sent to Kafka.
     */
    compressionType?: pulumi.Input<string>;
    /**
     * The identifier for the sink database in Materialize. Defaults to `MZ_DATABASE` environment variable if set or <span pulumi-lang-nodejs="`materialize`" pulumi-lang-dotnet="`Materialize`" pulumi-lang-go="`materialize`" pulumi-lang-python="`materialize`" pulumi-lang-yaml="`materialize`" pulumi-lang-java="`materialize`">`materialize`</span> if environment variable is not set.
     */
    databaseName?: pulumi.Input<string>;
    /**
     * How to interpret records (e.g. Debezium, Upsert).
     */
    envelope?: pulumi.Input<inputs.SinkKafkaEnvelope>;
    /**
     * How to decode raw bytes from different formats into data structures it can understand at runtime.
     */
    format?: pulumi.Input<inputs.SinkKafkaFormat>;
    /**
     * The name of the source, table or materialized view you want to send to the sink.
     */
    from?: pulumi.Input<inputs.SinkKafkaFrom>;
    /**
     * The name of a column containing additional headers to add to each message emitted by the sink. The column must be of type map[text => text] or map[text => bytea].
     */
    headers?: pulumi.Input<string>;
    /**
     * The name of the Kafka connection to use in the sink.
     */
    kafkaConnection?: pulumi.Input<inputs.SinkKafkaKafkaConnection>;
    /**
     * Disable Materialize's validation of the key's uniqueness.
     */
    keyNotEnforced?: pulumi.Input<boolean>;
    /**
     * An optional list of columns to use for the Kafka key. If unspecified, the Kafka key is left unset.
     */
    keys?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The identifier for the sink.
     */
    name?: pulumi.Input<string>;
    /**
     * The owernship role of the object.
     */
    ownershipRole?: pulumi.Input<string>;
    /**
     * A SQL expression used to partition the data in the Kafka sink. Can only be used with `ENVELOPE UPSERT`.
     */
    partitionBy?: pulumi.Input<string>;
    /**
     * The fully qualified name of the sink.
     */
    qualifiedSqlName?: pulumi.Input<string>;
    /**
     * The region to use for the resource connection. If not set, the default region is used.
     */
    region?: pulumi.Input<string>;
    /**
     * The identifier for the sink schema in Materialize. Defaults to <span pulumi-lang-nodejs="`public`" pulumi-lang-dotnet="`Public`" pulumi-lang-go="`public`" pulumi-lang-python="`public`" pulumi-lang-yaml="`public`" pulumi-lang-java="`public`">`public`</span>.
     */
    schemaName?: pulumi.Input<string>;
    sinkKafkaId?: pulumi.Input<string>;
    /**
     * The size of the cluster maintaining this sink.
     */
    size?: pulumi.Input<string>;
    /**
     * Whether to emit the consolidated results of the query before the sink was created at the start of the sink.
     */
    snapshot?: pulumi.Input<boolean>;
    /**
     * The Kafka topic you want to subscribe to.
     */
    topic?: pulumi.Input<string>;
    /**
     * Any topic-level configs to use when creating the Kafka topic (if the Kafka topic does not already exist).
     */
    topicConfig?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * The partition count to use when creating the Kafka topic (if the Kafka topic does not already exist).
     */
    topicPartitionCount?: pulumi.Input<number>;
    /**
     * The replication factor to use when creating the Kafka topic (if the Kafka topic does not already exist).
     */
    topicReplicationFactor?: pulumi.Input<number>;
}

/**
 * The set of arguments for constructing a SinkKafka resource.
 */
export interface SinkKafkaArgs {
    /**
     * The cluster to maintain this sink.
     */
    clusterName?: pulumi.Input<string>;
    /**
     * Comment on an object in the database.
     */
    comment?: pulumi.Input<string>;
    /**
     * The type of compression to apply to messages before they are sent to Kafka.
     */
    compressionType?: pulumi.Input<string>;
    /**
     * The identifier for the sink database in Materialize. Defaults to `MZ_DATABASE` environment variable if set or <span pulumi-lang-nodejs="`materialize`" pulumi-lang-dotnet="`Materialize`" pulumi-lang-go="`materialize`" pulumi-lang-python="`materialize`" pulumi-lang-yaml="`materialize`" pulumi-lang-java="`materialize`">`materialize`</span> if environment variable is not set.
     */
    databaseName?: pulumi.Input<string>;
    /**
     * How to interpret records (e.g. Debezium, Upsert).
     */
    envelope?: pulumi.Input<inputs.SinkKafkaEnvelope>;
    /**
     * How to decode raw bytes from different formats into data structures it can understand at runtime.
     */
    format?: pulumi.Input<inputs.SinkKafkaFormat>;
    /**
     * The name of the source, table or materialized view you want to send to the sink.
     */
    from: pulumi.Input<inputs.SinkKafkaFrom>;
    /**
     * The name of a column containing additional headers to add to each message emitted by the sink. The column must be of type map[text => text] or map[text => bytea].
     */
    headers?: pulumi.Input<string>;
    /**
     * The name of the Kafka connection to use in the sink.
     */
    kafkaConnection: pulumi.Input<inputs.SinkKafkaKafkaConnection>;
    /**
     * Disable Materialize's validation of the key's uniqueness.
     */
    keyNotEnforced?: pulumi.Input<boolean>;
    /**
     * An optional list of columns to use for the Kafka key. If unspecified, the Kafka key is left unset.
     */
    keys?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The identifier for the sink.
     */
    name?: pulumi.Input<string>;
    /**
     * The owernship role of the object.
     */
    ownershipRole?: pulumi.Input<string>;
    /**
     * A SQL expression used to partition the data in the Kafka sink. Can only be used with `ENVELOPE UPSERT`.
     */
    partitionBy?: pulumi.Input<string>;
    /**
     * The region to use for the resource connection. If not set, the default region is used.
     */
    region?: pulumi.Input<string>;
    /**
     * The identifier for the sink schema in Materialize. Defaults to <span pulumi-lang-nodejs="`public`" pulumi-lang-dotnet="`Public`" pulumi-lang-go="`public`" pulumi-lang-python="`public`" pulumi-lang-yaml="`public`" pulumi-lang-java="`public`">`public`</span>.
     */
    schemaName?: pulumi.Input<string>;
    sinkKafkaId?: pulumi.Input<string>;
    /**
     * Whether to emit the consolidated results of the query before the sink was created at the start of the sink.
     */
    snapshot?: pulumi.Input<boolean>;
    /**
     * The Kafka topic you want to subscribe to.
     */
    topic: pulumi.Input<string>;
    /**
     * Any topic-level configs to use when creating the Kafka topic (if the Kafka topic does not already exist).
     */
    topicConfig?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * The partition count to use when creating the Kafka topic (if the Kafka topic does not already exist).
     */
    topicPartitionCount?: pulumi.Input<number>;
    /**
     * The replication factor to use when creating the Kafka topic (if the Kafka topic does not already exist).
     */
    topicReplicationFactor?: pulumi.Input<number>;
}
