// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class SourceGrant extends pulumi.CustomResource {
    /**
     * Get an existing SourceGrant resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SourceGrantState, opts?: pulumi.CustomResourceOptions): SourceGrant {
        return new SourceGrant(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'materialize:index/sourceGrant:SourceGrant';

    /**
     * Returns true if the given object is an instance of SourceGrant.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SourceGrant {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SourceGrant.__pulumiType;
    }

    /**
     * The database that the view belongs to.
     */
    declare public readonly databaseName: pulumi.Output<string>;
    /**
     * The privilege to grant to the object.
     */
    declare public readonly privilege: pulumi.Output<string>;
    /**
     * The region to use for the resource connection. If not set, the default region is used.
     */
    declare public readonly region: pulumi.Output<string>;
    /**
     * The name of the role to grant privilege to.
     */
    declare public readonly roleName: pulumi.Output<string>;
    /**
     * The schema that the view being to.
     */
    declare public readonly schemaName: pulumi.Output<string>;
    declare public readonly sourceGrantId: pulumi.Output<string>;
    /**
     * The source that is being granted on.
     */
    declare public readonly sourceName: pulumi.Output<string>;

    /**
     * Create a SourceGrant resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SourceGrantArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SourceGrantArgs | SourceGrantState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SourceGrantState | undefined;
            resourceInputs["databaseName"] = state?.databaseName;
            resourceInputs["privilege"] = state?.privilege;
            resourceInputs["region"] = state?.region;
            resourceInputs["roleName"] = state?.roleName;
            resourceInputs["schemaName"] = state?.schemaName;
            resourceInputs["sourceGrantId"] = state?.sourceGrantId;
            resourceInputs["sourceName"] = state?.sourceName;
        } else {
            const args = argsOrState as SourceGrantArgs | undefined;
            if (args?.databaseName === undefined && !opts.urn) {
                throw new Error("Missing required property 'databaseName'");
            }
            if (args?.privilege === undefined && !opts.urn) {
                throw new Error("Missing required property 'privilege'");
            }
            if (args?.roleName === undefined && !opts.urn) {
                throw new Error("Missing required property 'roleName'");
            }
            if (args?.schemaName === undefined && !opts.urn) {
                throw new Error("Missing required property 'schemaName'");
            }
            if (args?.sourceName === undefined && !opts.urn) {
                throw new Error("Missing required property 'sourceName'");
            }
            resourceInputs["databaseName"] = args?.databaseName;
            resourceInputs["privilege"] = args?.privilege;
            resourceInputs["region"] = args?.region;
            resourceInputs["roleName"] = args?.roleName;
            resourceInputs["schemaName"] = args?.schemaName;
            resourceInputs["sourceGrantId"] = args?.sourceGrantId;
            resourceInputs["sourceName"] = args?.sourceName;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(SourceGrant.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering SourceGrant resources.
 */
export interface SourceGrantState {
    /**
     * The database that the view belongs to.
     */
    databaseName?: pulumi.Input<string>;
    /**
     * The privilege to grant to the object.
     */
    privilege?: pulumi.Input<string>;
    /**
     * The region to use for the resource connection. If not set, the default region is used.
     */
    region?: pulumi.Input<string>;
    /**
     * The name of the role to grant privilege to.
     */
    roleName?: pulumi.Input<string>;
    /**
     * The schema that the view being to.
     */
    schemaName?: pulumi.Input<string>;
    sourceGrantId?: pulumi.Input<string>;
    /**
     * The source that is being granted on.
     */
    sourceName?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a SourceGrant resource.
 */
export interface SourceGrantArgs {
    /**
     * The database that the view belongs to.
     */
    databaseName: pulumi.Input<string>;
    /**
     * The privilege to grant to the object.
     */
    privilege: pulumi.Input<string>;
    /**
     * The region to use for the resource connection. If not set, the default region is used.
     */
    region?: pulumi.Input<string>;
    /**
     * The name of the role to grant privilege to.
     */
    roleName: pulumi.Input<string>;
    /**
     * The schema that the view being to.
     */
    schemaName: pulumi.Input<string>;
    sourceGrantId?: pulumi.Input<string>;
    /**
     * The source that is being granted on.
     */
    sourceName: pulumi.Input<string>;
}
