// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class SourceWebhook extends pulumi.CustomResource {
    /**
     * Get an existing SourceWebhook resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SourceWebhookState, opts?: pulumi.CustomResourceOptions): SourceWebhook {
        return new SourceWebhook(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'materialize:index/sourceWebhook:SourceWebhook';

    /**
     * Returns true if the given object is an instance of SourceWebhook.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SourceWebhook {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SourceWebhook.__pulumiType;
    }

    /**
     * The body format of the webhook.
     */
    declare public readonly bodyFormat: pulumi.Output<string>;
    /**
     * The check expression for the webhook.
     */
    declare public readonly checkExpression: pulumi.Output<string | undefined>;
    /**
     * The check options for the webhook.
     */
    declare public readonly checkOptions: pulumi.Output<outputs.SourceWebhookCheckOption[] | undefined>;
    /**
     * The cluster to maintain this source.
     */
    declare public readonly clusterName: pulumi.Output<string | undefined>;
    /**
     * Comment on an object in the database.
     */
    declare public readonly comment: pulumi.Output<string | undefined>;
    /**
     * The identifier for the source database in Materialize. Defaults to `MZ_DATABASE` environment variable if set or <span pulumi-lang-nodejs="`materialize`" pulumi-lang-dotnet="`Materialize`" pulumi-lang-go="`materialize`" pulumi-lang-python="`materialize`" pulumi-lang-yaml="`materialize`" pulumi-lang-java="`materialize`">`materialize`</span> if environment variable is not set.
     */
    declare public readonly databaseName: pulumi.Output<string | undefined>;
    /**
     * Map a header value from a request into a column.
     */
    declare public readonly includeHeader: pulumi.Output<outputs.SourceWebhookIncludeHeader[] | undefined>;
    /**
     * Include headers in the webhook.
     */
    declare public readonly includeHeaders: pulumi.Output<outputs.SourceWebhookIncludeHeaders | undefined>;
    /**
     * The identifier for the source.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The owernship role of the object.
     */
    declare public readonly ownershipRole: pulumi.Output<string>;
    /**
     * The fully qualified name of the source.
     */
    declare public /*out*/ readonly qualifiedSqlName: pulumi.Output<string>;
    /**
     * The region to use for the resource connection. If not set, the default region is used.
     */
    declare public readonly region: pulumi.Output<string>;
    /**
     * The identifier for the source schema in Materialize. Defaults to <span pulumi-lang-nodejs="`public`" pulumi-lang-dotnet="`Public`" pulumi-lang-go="`public`" pulumi-lang-python="`public`" pulumi-lang-yaml="`public`" pulumi-lang-java="`public`">`public`</span>.
     */
    declare public readonly schemaName: pulumi.Output<string | undefined>;
    /**
     * The size of the cluster maintaining this source.
     */
    declare public /*out*/ readonly size: pulumi.Output<string>;
    declare public readonly sourceWebhookId: pulumi.Output<string>;
    /**
     * The webhook URL that can be used to send data to this source.
     */
    declare public /*out*/ readonly url: pulumi.Output<string>;

    /**
     * Create a SourceWebhook resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SourceWebhookArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SourceWebhookArgs | SourceWebhookState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SourceWebhookState | undefined;
            resourceInputs["bodyFormat"] = state?.bodyFormat;
            resourceInputs["checkExpression"] = state?.checkExpression;
            resourceInputs["checkOptions"] = state?.checkOptions;
            resourceInputs["clusterName"] = state?.clusterName;
            resourceInputs["comment"] = state?.comment;
            resourceInputs["databaseName"] = state?.databaseName;
            resourceInputs["includeHeader"] = state?.includeHeader;
            resourceInputs["includeHeaders"] = state?.includeHeaders;
            resourceInputs["name"] = state?.name;
            resourceInputs["ownershipRole"] = state?.ownershipRole;
            resourceInputs["qualifiedSqlName"] = state?.qualifiedSqlName;
            resourceInputs["region"] = state?.region;
            resourceInputs["schemaName"] = state?.schemaName;
            resourceInputs["size"] = state?.size;
            resourceInputs["sourceWebhookId"] = state?.sourceWebhookId;
            resourceInputs["url"] = state?.url;
        } else {
            const args = argsOrState as SourceWebhookArgs | undefined;
            if (args?.bodyFormat === undefined && !opts.urn) {
                throw new Error("Missing required property 'bodyFormat'");
            }
            resourceInputs["bodyFormat"] = args?.bodyFormat;
            resourceInputs["checkExpression"] = args?.checkExpression;
            resourceInputs["checkOptions"] = args?.checkOptions;
            resourceInputs["clusterName"] = args?.clusterName;
            resourceInputs["comment"] = args?.comment;
            resourceInputs["databaseName"] = args?.databaseName;
            resourceInputs["includeHeader"] = args?.includeHeader;
            resourceInputs["includeHeaders"] = args?.includeHeaders;
            resourceInputs["name"] = args?.name;
            resourceInputs["ownershipRole"] = args?.ownershipRole;
            resourceInputs["region"] = args?.region;
            resourceInputs["schemaName"] = args?.schemaName;
            resourceInputs["sourceWebhookId"] = args?.sourceWebhookId;
            resourceInputs["qualifiedSqlName"] = undefined /*out*/;
            resourceInputs["size"] = undefined /*out*/;
            resourceInputs["url"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(SourceWebhook.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering SourceWebhook resources.
 */
export interface SourceWebhookState {
    /**
     * The body format of the webhook.
     */
    bodyFormat?: pulumi.Input<string>;
    /**
     * The check expression for the webhook.
     */
    checkExpression?: pulumi.Input<string>;
    /**
     * The check options for the webhook.
     */
    checkOptions?: pulumi.Input<pulumi.Input<inputs.SourceWebhookCheckOption>[]>;
    /**
     * The cluster to maintain this source.
     */
    clusterName?: pulumi.Input<string>;
    /**
     * Comment on an object in the database.
     */
    comment?: pulumi.Input<string>;
    /**
     * The identifier for the source database in Materialize. Defaults to `MZ_DATABASE` environment variable if set or <span pulumi-lang-nodejs="`materialize`" pulumi-lang-dotnet="`Materialize`" pulumi-lang-go="`materialize`" pulumi-lang-python="`materialize`" pulumi-lang-yaml="`materialize`" pulumi-lang-java="`materialize`">`materialize`</span> if environment variable is not set.
     */
    databaseName?: pulumi.Input<string>;
    /**
     * Map a header value from a request into a column.
     */
    includeHeader?: pulumi.Input<pulumi.Input<inputs.SourceWebhookIncludeHeader>[]>;
    /**
     * Include headers in the webhook.
     */
    includeHeaders?: pulumi.Input<inputs.SourceWebhookIncludeHeaders>;
    /**
     * The identifier for the source.
     */
    name?: pulumi.Input<string>;
    /**
     * The owernship role of the object.
     */
    ownershipRole?: pulumi.Input<string>;
    /**
     * The fully qualified name of the source.
     */
    qualifiedSqlName?: pulumi.Input<string>;
    /**
     * The region to use for the resource connection. If not set, the default region is used.
     */
    region?: pulumi.Input<string>;
    /**
     * The identifier for the source schema in Materialize. Defaults to <span pulumi-lang-nodejs="`public`" pulumi-lang-dotnet="`Public`" pulumi-lang-go="`public`" pulumi-lang-python="`public`" pulumi-lang-yaml="`public`" pulumi-lang-java="`public`">`public`</span>.
     */
    schemaName?: pulumi.Input<string>;
    /**
     * The size of the cluster maintaining this source.
     */
    size?: pulumi.Input<string>;
    sourceWebhookId?: pulumi.Input<string>;
    /**
     * The webhook URL that can be used to send data to this source.
     */
    url?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a SourceWebhook resource.
 */
export interface SourceWebhookArgs {
    /**
     * The body format of the webhook.
     */
    bodyFormat: pulumi.Input<string>;
    /**
     * The check expression for the webhook.
     */
    checkExpression?: pulumi.Input<string>;
    /**
     * The check options for the webhook.
     */
    checkOptions?: pulumi.Input<pulumi.Input<inputs.SourceWebhookCheckOption>[]>;
    /**
     * The cluster to maintain this source.
     */
    clusterName?: pulumi.Input<string>;
    /**
     * Comment on an object in the database.
     */
    comment?: pulumi.Input<string>;
    /**
     * The identifier for the source database in Materialize. Defaults to `MZ_DATABASE` environment variable if set or <span pulumi-lang-nodejs="`materialize`" pulumi-lang-dotnet="`Materialize`" pulumi-lang-go="`materialize`" pulumi-lang-python="`materialize`" pulumi-lang-yaml="`materialize`" pulumi-lang-java="`materialize`">`materialize`</span> if environment variable is not set.
     */
    databaseName?: pulumi.Input<string>;
    /**
     * Map a header value from a request into a column.
     */
    includeHeader?: pulumi.Input<pulumi.Input<inputs.SourceWebhookIncludeHeader>[]>;
    /**
     * Include headers in the webhook.
     */
    includeHeaders?: pulumi.Input<inputs.SourceWebhookIncludeHeaders>;
    /**
     * The identifier for the source.
     */
    name?: pulumi.Input<string>;
    /**
     * The owernship role of the object.
     */
    ownershipRole?: pulumi.Input<string>;
    /**
     * The region to use for the resource connection. If not set, the default region is used.
     */
    region?: pulumi.Input<string>;
    /**
     * The identifier for the source schema in Materialize. Defaults to <span pulumi-lang-nodejs="`public`" pulumi-lang-dotnet="`Public`" pulumi-lang-go="`public`" pulumi-lang-python="`public`" pulumi-lang-yaml="`public`" pulumi-lang-java="`public`">`public`</span>.
     */
    schemaName?: pulumi.Input<string>;
    sourceWebhookId?: pulumi.Input<string>;
}
