// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class SourcePostgres extends pulumi.CustomResource {
    /**
     * Get an existing SourcePostgres resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SourcePostgresState, opts?: pulumi.CustomResourceOptions): SourcePostgres {
        return new SourcePostgres(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'materialize:index/sourcePostgres:SourcePostgres';

    /**
     * Returns true if the given object is an instance of SourcePostgres.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SourcePostgres {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SourcePostgres.__pulumiType;
    }

    /**
     * The cluster to maintain this source.
     */
    declare public readonly clusterName: pulumi.Output<string>;
    /**
     * Comment on an object in the database.
     */
    declare public readonly comment: pulumi.Output<string | undefined>;
    /**
     * The identifier for the source database in Materialize. Defaults to `MZ_DATABASE` environment variable if set or <span pulumi-lang-nodejs="`materialize`" pulumi-lang-dotnet="`Materialize`" pulumi-lang-go="`materialize`" pulumi-lang-python="`materialize`" pulumi-lang-yaml="`materialize`" pulumi-lang-java="`materialize`">`materialize`</span> if environment variable is not set.
     */
    declare public readonly databaseName: pulumi.Output<string | undefined>;
    /**
     * Exclude specific columns when reading data from PostgreSQL. Can only be updated in place when also updating a corresponding <span pulumi-lang-nodejs="`table`" pulumi-lang-dotnet="`Table`" pulumi-lang-go="`table`" pulumi-lang-python="`table`" pulumi-lang-yaml="`table`" pulumi-lang-java="`table`">`table`</span> attribute.
     */
    declare public readonly excludeColumns: pulumi.Output<string[] | undefined>;
    /**
     * The name of the progress collection for the source. If this is not specified, the collection will be named `<src_name>_progress`.
     */
    declare public readonly exposeProgress: pulumi.Output<outputs.SourcePostgresExposeProgress | undefined>;
    /**
     * The identifier for the source.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The owernship role of the object.
     */
    declare public readonly ownershipRole: pulumi.Output<string>;
    /**
     * The PostgreSQL connection to use in the source.
     */
    declare public readonly postgresConnection: pulumi.Output<outputs.SourcePostgresPostgresConnection>;
    /**
     * The PostgreSQL publication (the replication data set containing the tables to be streamed to Materialize).
     */
    declare public readonly publication: pulumi.Output<string>;
    /**
     * The fully qualified name of the source.
     */
    declare public /*out*/ readonly qualifiedSqlName: pulumi.Output<string>;
    /**
     * The region to use for the resource connection. If not set, the default region is used.
     */
    declare public readonly region: pulumi.Output<string>;
    /**
     * The identifier for the source schema in Materialize. Defaults to <span pulumi-lang-nodejs="`public`" pulumi-lang-dotnet="`Public`" pulumi-lang-go="`public`" pulumi-lang-python="`public`" pulumi-lang-yaml="`public`" pulumi-lang-java="`public`">`public`</span>.
     */
    declare public readonly schemaName: pulumi.Output<string | undefined>;
    /**
     * The size of the cluster maintaining this source.
     */
    declare public /*out*/ readonly size: pulumi.Output<string>;
    declare public readonly sourcePostgresId: pulumi.Output<string>;
    /**
     * Creates subsources for specific tables in the Postgres connection.
     */
    declare public readonly tables: pulumi.Output<outputs.SourcePostgresTable[]>;
    /**
     * Decode data as text for specific columns that contain PostgreSQL types that are unsupported in Materialize. Can only be updated in place when also updating a corresponding <span pulumi-lang-nodejs="`table`" pulumi-lang-dotnet="`Table`" pulumi-lang-go="`table`" pulumi-lang-python="`table`" pulumi-lang-yaml="`table`" pulumi-lang-java="`table`">`table`</span> attribute.
     */
    declare public readonly textColumns: pulumi.Output<string[] | undefined>;

    /**
     * Create a SourcePostgres resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SourcePostgresArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SourcePostgresArgs | SourcePostgresState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SourcePostgresState | undefined;
            resourceInputs["clusterName"] = state?.clusterName;
            resourceInputs["comment"] = state?.comment;
            resourceInputs["databaseName"] = state?.databaseName;
            resourceInputs["excludeColumns"] = state?.excludeColumns;
            resourceInputs["exposeProgress"] = state?.exposeProgress;
            resourceInputs["name"] = state?.name;
            resourceInputs["ownershipRole"] = state?.ownershipRole;
            resourceInputs["postgresConnection"] = state?.postgresConnection;
            resourceInputs["publication"] = state?.publication;
            resourceInputs["qualifiedSqlName"] = state?.qualifiedSqlName;
            resourceInputs["region"] = state?.region;
            resourceInputs["schemaName"] = state?.schemaName;
            resourceInputs["size"] = state?.size;
            resourceInputs["sourcePostgresId"] = state?.sourcePostgresId;
            resourceInputs["tables"] = state?.tables;
            resourceInputs["textColumns"] = state?.textColumns;
        } else {
            const args = argsOrState as SourcePostgresArgs | undefined;
            if (args?.postgresConnection === undefined && !opts.urn) {
                throw new Error("Missing required property 'postgresConnection'");
            }
            if (args?.publication === undefined && !opts.urn) {
                throw new Error("Missing required property 'publication'");
            }
            if (args?.tables === undefined && !opts.urn) {
                throw new Error("Missing required property 'tables'");
            }
            resourceInputs["clusterName"] = args?.clusterName;
            resourceInputs["comment"] = args?.comment;
            resourceInputs["databaseName"] = args?.databaseName;
            resourceInputs["excludeColumns"] = args?.excludeColumns;
            resourceInputs["exposeProgress"] = args?.exposeProgress;
            resourceInputs["name"] = args?.name;
            resourceInputs["ownershipRole"] = args?.ownershipRole;
            resourceInputs["postgresConnection"] = args?.postgresConnection;
            resourceInputs["publication"] = args?.publication;
            resourceInputs["region"] = args?.region;
            resourceInputs["schemaName"] = args?.schemaName;
            resourceInputs["sourcePostgresId"] = args?.sourcePostgresId;
            resourceInputs["tables"] = args?.tables;
            resourceInputs["textColumns"] = args?.textColumns;
            resourceInputs["qualifiedSqlName"] = undefined /*out*/;
            resourceInputs["size"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(SourcePostgres.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering SourcePostgres resources.
 */
export interface SourcePostgresState {
    /**
     * The cluster to maintain this source.
     */
    clusterName?: pulumi.Input<string>;
    /**
     * Comment on an object in the database.
     */
    comment?: pulumi.Input<string>;
    /**
     * The identifier for the source database in Materialize. Defaults to `MZ_DATABASE` environment variable if set or <span pulumi-lang-nodejs="`materialize`" pulumi-lang-dotnet="`Materialize`" pulumi-lang-go="`materialize`" pulumi-lang-python="`materialize`" pulumi-lang-yaml="`materialize`" pulumi-lang-java="`materialize`">`materialize`</span> if environment variable is not set.
     */
    databaseName?: pulumi.Input<string>;
    /**
     * Exclude specific columns when reading data from PostgreSQL. Can only be updated in place when also updating a corresponding <span pulumi-lang-nodejs="`table`" pulumi-lang-dotnet="`Table`" pulumi-lang-go="`table`" pulumi-lang-python="`table`" pulumi-lang-yaml="`table`" pulumi-lang-java="`table`">`table`</span> attribute.
     */
    excludeColumns?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The name of the progress collection for the source. If this is not specified, the collection will be named `<src_name>_progress`.
     */
    exposeProgress?: pulumi.Input<inputs.SourcePostgresExposeProgress>;
    /**
     * The identifier for the source.
     */
    name?: pulumi.Input<string>;
    /**
     * The owernship role of the object.
     */
    ownershipRole?: pulumi.Input<string>;
    /**
     * The PostgreSQL connection to use in the source.
     */
    postgresConnection?: pulumi.Input<inputs.SourcePostgresPostgresConnection>;
    /**
     * The PostgreSQL publication (the replication data set containing the tables to be streamed to Materialize).
     */
    publication?: pulumi.Input<string>;
    /**
     * The fully qualified name of the source.
     */
    qualifiedSqlName?: pulumi.Input<string>;
    /**
     * The region to use for the resource connection. If not set, the default region is used.
     */
    region?: pulumi.Input<string>;
    /**
     * The identifier for the source schema in Materialize. Defaults to <span pulumi-lang-nodejs="`public`" pulumi-lang-dotnet="`Public`" pulumi-lang-go="`public`" pulumi-lang-python="`public`" pulumi-lang-yaml="`public`" pulumi-lang-java="`public`">`public`</span>.
     */
    schemaName?: pulumi.Input<string>;
    /**
     * The size of the cluster maintaining this source.
     */
    size?: pulumi.Input<string>;
    sourcePostgresId?: pulumi.Input<string>;
    /**
     * Creates subsources for specific tables in the Postgres connection.
     */
    tables?: pulumi.Input<pulumi.Input<inputs.SourcePostgresTable>[]>;
    /**
     * Decode data as text for specific columns that contain PostgreSQL types that are unsupported in Materialize. Can only be updated in place when also updating a corresponding <span pulumi-lang-nodejs="`table`" pulumi-lang-dotnet="`Table`" pulumi-lang-go="`table`" pulumi-lang-python="`table`" pulumi-lang-yaml="`table`" pulumi-lang-java="`table`">`table`</span> attribute.
     */
    textColumns?: pulumi.Input<pulumi.Input<string>[]>;
}

/**
 * The set of arguments for constructing a SourcePostgres resource.
 */
export interface SourcePostgresArgs {
    /**
     * The cluster to maintain this source.
     */
    clusterName?: pulumi.Input<string>;
    /**
     * Comment on an object in the database.
     */
    comment?: pulumi.Input<string>;
    /**
     * The identifier for the source database in Materialize. Defaults to `MZ_DATABASE` environment variable if set or <span pulumi-lang-nodejs="`materialize`" pulumi-lang-dotnet="`Materialize`" pulumi-lang-go="`materialize`" pulumi-lang-python="`materialize`" pulumi-lang-yaml="`materialize`" pulumi-lang-java="`materialize`">`materialize`</span> if environment variable is not set.
     */
    databaseName?: pulumi.Input<string>;
    /**
     * Exclude specific columns when reading data from PostgreSQL. Can only be updated in place when also updating a corresponding <span pulumi-lang-nodejs="`table`" pulumi-lang-dotnet="`Table`" pulumi-lang-go="`table`" pulumi-lang-python="`table`" pulumi-lang-yaml="`table`" pulumi-lang-java="`table`">`table`</span> attribute.
     */
    excludeColumns?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The name of the progress collection for the source. If this is not specified, the collection will be named `<src_name>_progress`.
     */
    exposeProgress?: pulumi.Input<inputs.SourcePostgresExposeProgress>;
    /**
     * The identifier for the source.
     */
    name?: pulumi.Input<string>;
    /**
     * The owernship role of the object.
     */
    ownershipRole?: pulumi.Input<string>;
    /**
     * The PostgreSQL connection to use in the source.
     */
    postgresConnection: pulumi.Input<inputs.SourcePostgresPostgresConnection>;
    /**
     * The PostgreSQL publication (the replication data set containing the tables to be streamed to Materialize).
     */
    publication: pulumi.Input<string>;
    /**
     * The region to use for the resource connection. If not set, the default region is used.
     */
    region?: pulumi.Input<string>;
    /**
     * The identifier for the source schema in Materialize. Defaults to <span pulumi-lang-nodejs="`public`" pulumi-lang-dotnet="`Public`" pulumi-lang-go="`public`" pulumi-lang-python="`public`" pulumi-lang-yaml="`public`" pulumi-lang-java="`public`">`public`</span>.
     */
    schemaName?: pulumi.Input<string>;
    sourcePostgresId?: pulumi.Input<string>;
    /**
     * Creates subsources for specific tables in the Postgres connection.
     */
    tables: pulumi.Input<pulumi.Input<inputs.SourcePostgresTable>[]>;
    /**
     * Decode data as text for specific columns that contain PostgreSQL types that are unsupported in Materialize. Can only be updated in place when also updating a corresponding <span pulumi-lang-nodejs="`table`" pulumi-lang-dotnet="`Table`" pulumi-lang-go="`table`" pulumi-lang-python="`table`" pulumi-lang-yaml="`table`" pulumi-lang-java="`table`">`table`</span> attribute.
     */
    textColumns?: pulumi.Input<pulumi.Input<string>[]>;
}
