// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Type extends pulumi.CustomResource {
    /**
     * Get an existing Type resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: TypeState, opts?: pulumi.CustomResourceOptions): Type {
        return new Type(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'materialize:index/type:Type';

    /**
     * Returns true if the given object is an instance of Type.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Type {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Type.__pulumiType;
    }

    /**
     * Type category.
     */
    declare public /*out*/ readonly category: pulumi.Output<string>;
    /**
     * Comment on an object in the database.
     */
    declare public readonly comment: pulumi.Output<string | undefined>;
    /**
     * The identifier for the type database in Materialize. Defaults to `MZ_DATABASE` environment variable if set or <span pulumi-lang-nodejs="`materialize`" pulumi-lang-dotnet="`Materialize`" pulumi-lang-go="`materialize`" pulumi-lang-python="`materialize`" pulumi-lang-yaml="`materialize`" pulumi-lang-java="`materialize`">`materialize`</span> if environment variable is not set.
     */
    declare public readonly databaseName: pulumi.Output<string | undefined>;
    /**
     * List properties.
     */
    declare public readonly listProperties: pulumi.Output<outputs.TypeListProperties | undefined>;
    /**
     * Map properties.
     */
    declare public readonly mapProperties: pulumi.Output<outputs.TypeMapProperties | undefined>;
    /**
     * The identifier for the type.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The owernship role of the object.
     */
    declare public readonly ownershipRole: pulumi.Output<string>;
    /**
     * The fully qualified name of the type.
     */
    declare public /*out*/ readonly qualifiedSqlName: pulumi.Output<string>;
    /**
     * The region to use for the resource connection. If not set, the default region is used.
     */
    declare public readonly region: pulumi.Output<string>;
    /**
     * Row properties.
     */
    declare public readonly rowProperties: pulumi.Output<outputs.TypeRowProperty[] | undefined>;
    /**
     * The identifier for the type schema in Materialize. Defaults to <span pulumi-lang-nodejs="`public`" pulumi-lang-dotnet="`Public`" pulumi-lang-go="`public`" pulumi-lang-python="`public`" pulumi-lang-yaml="`public`" pulumi-lang-java="`public`">`public`</span>.
     */
    declare public readonly schemaName: pulumi.Output<string | undefined>;
    declare public readonly typeId: pulumi.Output<string>;

    /**
     * Create a Type resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: TypeArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: TypeArgs | TypeState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as TypeState | undefined;
            resourceInputs["category"] = state?.category;
            resourceInputs["comment"] = state?.comment;
            resourceInputs["databaseName"] = state?.databaseName;
            resourceInputs["listProperties"] = state?.listProperties;
            resourceInputs["mapProperties"] = state?.mapProperties;
            resourceInputs["name"] = state?.name;
            resourceInputs["ownershipRole"] = state?.ownershipRole;
            resourceInputs["qualifiedSqlName"] = state?.qualifiedSqlName;
            resourceInputs["region"] = state?.region;
            resourceInputs["rowProperties"] = state?.rowProperties;
            resourceInputs["schemaName"] = state?.schemaName;
            resourceInputs["typeId"] = state?.typeId;
        } else {
            const args = argsOrState as TypeArgs | undefined;
            resourceInputs["comment"] = args?.comment;
            resourceInputs["databaseName"] = args?.databaseName;
            resourceInputs["listProperties"] = args?.listProperties;
            resourceInputs["mapProperties"] = args?.mapProperties;
            resourceInputs["name"] = args?.name;
            resourceInputs["ownershipRole"] = args?.ownershipRole;
            resourceInputs["region"] = args?.region;
            resourceInputs["rowProperties"] = args?.rowProperties;
            resourceInputs["schemaName"] = args?.schemaName;
            resourceInputs["typeId"] = args?.typeId;
            resourceInputs["category"] = undefined /*out*/;
            resourceInputs["qualifiedSqlName"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Type.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Type resources.
 */
export interface TypeState {
    /**
     * Type category.
     */
    category?: pulumi.Input<string>;
    /**
     * Comment on an object in the database.
     */
    comment?: pulumi.Input<string>;
    /**
     * The identifier for the type database in Materialize. Defaults to `MZ_DATABASE` environment variable if set or <span pulumi-lang-nodejs="`materialize`" pulumi-lang-dotnet="`Materialize`" pulumi-lang-go="`materialize`" pulumi-lang-python="`materialize`" pulumi-lang-yaml="`materialize`" pulumi-lang-java="`materialize`">`materialize`</span> if environment variable is not set.
     */
    databaseName?: pulumi.Input<string>;
    /**
     * List properties.
     */
    listProperties?: pulumi.Input<inputs.TypeListProperties>;
    /**
     * Map properties.
     */
    mapProperties?: pulumi.Input<inputs.TypeMapProperties>;
    /**
     * The identifier for the type.
     */
    name?: pulumi.Input<string>;
    /**
     * The owernship role of the object.
     */
    ownershipRole?: pulumi.Input<string>;
    /**
     * The fully qualified name of the type.
     */
    qualifiedSqlName?: pulumi.Input<string>;
    /**
     * The region to use for the resource connection. If not set, the default region is used.
     */
    region?: pulumi.Input<string>;
    /**
     * Row properties.
     */
    rowProperties?: pulumi.Input<pulumi.Input<inputs.TypeRowProperty>[]>;
    /**
     * The identifier for the type schema in Materialize. Defaults to <span pulumi-lang-nodejs="`public`" pulumi-lang-dotnet="`Public`" pulumi-lang-go="`public`" pulumi-lang-python="`public`" pulumi-lang-yaml="`public`" pulumi-lang-java="`public`">`public`</span>.
     */
    schemaName?: pulumi.Input<string>;
    typeId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Type resource.
 */
export interface TypeArgs {
    /**
     * Comment on an object in the database.
     */
    comment?: pulumi.Input<string>;
    /**
     * The identifier for the type database in Materialize. Defaults to `MZ_DATABASE` environment variable if set or <span pulumi-lang-nodejs="`materialize`" pulumi-lang-dotnet="`Materialize`" pulumi-lang-go="`materialize`" pulumi-lang-python="`materialize`" pulumi-lang-yaml="`materialize`" pulumi-lang-java="`materialize`">`materialize`</span> if environment variable is not set.
     */
    databaseName?: pulumi.Input<string>;
    /**
     * List properties.
     */
    listProperties?: pulumi.Input<inputs.TypeListProperties>;
    /**
     * Map properties.
     */
    mapProperties?: pulumi.Input<inputs.TypeMapProperties>;
    /**
     * The identifier for the type.
     */
    name?: pulumi.Input<string>;
    /**
     * The owernship role of the object.
     */
    ownershipRole?: pulumi.Input<string>;
    /**
     * The region to use for the resource connection. If not set, the default region is used.
     */
    region?: pulumi.Input<string>;
    /**
     * Row properties.
     */
    rowProperties?: pulumi.Input<pulumi.Input<inputs.TypeRowProperty>[]>;
    /**
     * The identifier for the type schema in Materialize. Defaults to <span pulumi-lang-nodejs="`public`" pulumi-lang-dotnet="`Public`" pulumi-lang-go="`public`" pulumi-lang-python="`public`" pulumi-lang-yaml="`public`" pulumi-lang-java="`public`">`public`</span>.
     */
    schemaName?: pulumi.Input<string>;
    typeId?: pulumi.Input<string>;
}
