// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class User extends pulumi.CustomResource {
    /**
     * Get an existing User resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: UserState, opts?: pulumi.CustomResourceOptions): User {
        return new User(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'materialize:index/user:User';

    /**
     * Returns true if the given object is an instance of User.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is User {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === User.__pulumiType;
    }

    /**
     * The authentication provider for the user.
     */
    declare public /*out*/ readonly authProvider: pulumi.Output<string>;
    /**
     * The email address of the user. This must be unique across all users in the organization.
     */
    declare public readonly email: pulumi.Output<string>;
    declare public /*out*/ readonly metadata: pulumi.Output<string>;
    /**
     * The roles to assign to the user. Allowed values are 'Member' and 'Admin'.
     */
    declare public readonly roles: pulumi.Output<string[]>;
    /**
     * Whether to send an email either inviting the user to activate their account, if the user is new, or inviting the user to join the organization, if the user already exists in another organization. Changing this property after the resource is created has no effect.
     */
    declare public readonly sendActivationEmail: pulumi.Output<boolean | undefined>;
    declare public readonly userId: pulumi.Output<string>;
    declare public /*out*/ readonly verified: pulumi.Output<boolean>;

    /**
     * Create a User resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: UserArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: UserArgs | UserState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as UserState | undefined;
            resourceInputs["authProvider"] = state?.authProvider;
            resourceInputs["email"] = state?.email;
            resourceInputs["metadata"] = state?.metadata;
            resourceInputs["roles"] = state?.roles;
            resourceInputs["sendActivationEmail"] = state?.sendActivationEmail;
            resourceInputs["userId"] = state?.userId;
            resourceInputs["verified"] = state?.verified;
        } else {
            const args = argsOrState as UserArgs | undefined;
            if (args?.email === undefined && !opts.urn) {
                throw new Error("Missing required property 'email'");
            }
            if (args?.roles === undefined && !opts.urn) {
                throw new Error("Missing required property 'roles'");
            }
            resourceInputs["email"] = args?.email;
            resourceInputs["roles"] = args?.roles;
            resourceInputs["sendActivationEmail"] = args?.sendActivationEmail;
            resourceInputs["userId"] = args?.userId;
            resourceInputs["authProvider"] = undefined /*out*/;
            resourceInputs["metadata"] = undefined /*out*/;
            resourceInputs["verified"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(User.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering User resources.
 */
export interface UserState {
    /**
     * The authentication provider for the user.
     */
    authProvider?: pulumi.Input<string>;
    /**
     * The email address of the user. This must be unique across all users in the organization.
     */
    email?: pulumi.Input<string>;
    metadata?: pulumi.Input<string>;
    /**
     * The roles to assign to the user. Allowed values are 'Member' and 'Admin'.
     */
    roles?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Whether to send an email either inviting the user to activate their account, if the user is new, or inviting the user to join the organization, if the user already exists in another organization. Changing this property after the resource is created has no effect.
     */
    sendActivationEmail?: pulumi.Input<boolean>;
    userId?: pulumi.Input<string>;
    verified?: pulumi.Input<boolean>;
}

/**
 * The set of arguments for constructing a User resource.
 */
export interface UserArgs {
    /**
     * The email address of the user. This must be unique across all users in the organization.
     */
    email: pulumi.Input<string>;
    /**
     * The roles to assign to the user. Allowed values are 'Member' and 'Admin'.
     */
    roles: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Whether to send an email either inviting the user to activate their account, if the user is new, or inviting the user to join the organization, if the user already exists in another organization. Changing this property after the resource is created has no effect.
     */
    sendActivationEmail?: pulumi.Input<boolean>;
    userId?: pulumi.Input<string>;
}
