// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("materialize");

/**
 * The base endpoint for Materialize.
 */
export declare const baseEndpoint: string | undefined;
Object.defineProperty(exports, "baseEndpoint", {
    get() {
        return __config.get("baseEndpoint");
    },
    enumerable: true,
});

/**
 * The endpoint for the Materialize Cloud API.
 */
export declare const cloudEndpoint: string | undefined;
Object.defineProperty(exports, "cloudEndpoint", {
    get() {
        return __config.get("cloudEndpoint");
    },
    enumerable: true,
});

/**
 * The Materialize database. Can also come from the `MZ_DATABASE` environment variable. Defaults to <span pulumi-lang-nodejs="`materialize`" pulumi-lang-dotnet="`Materialize`" pulumi-lang-go="`materialize`" pulumi-lang-python="`materialize`" pulumi-lang-yaml="`materialize`" pulumi-lang-java="`materialize`">`materialize`</span>.
 */
export declare const database: string | undefined;
Object.defineProperty(exports, "database", {
    get() {
        return __config.get("database");
    },
    enumerable: true,
});

/**
 * The default region if not specified in the resource
 */
export declare const defaultRegion: string | undefined;
Object.defineProperty(exports, "defaultRegion", {
    get() {
        return __config.get("defaultRegion");
    },
    enumerable: true,
});

/**
 * The endpoint for the Materialize API.
 */
export declare const endpoint: string | undefined;
Object.defineProperty(exports, "endpoint", {
    get() {
        return __config.get("endpoint");
    },
    enumerable: true,
});

/**
 * The Materialize host. Can also come from the `MZ_HOST` environment variable.
 */
export declare const host: string | undefined;
Object.defineProperty(exports, "host", {
    get() {
        return __config.get("host");
    },
    enumerable: true,
});

/**
 * Materialize host. Can also come from the `MZ_PASSWORD` environment variable.
 */
export declare const password: string | undefined;
Object.defineProperty(exports, "password", {
    get() {
        return __config.get("password");
    },
    enumerable: true,
});

/**
 * The Materialize SQL port. Can also come from the `MZ_PORT` environment variable.
 */
export declare const port: number | undefined;
Object.defineProperty(exports, "port", {
    get() {
        return __config.getObject<number>("port");
    },
    enumerable: true,
});

/**
 * For testing purposes, the SSL mode to use.
 */
export declare const sslmode: string | undefined;
Object.defineProperty(exports, "sslmode", {
    get() {
        return __config.get("sslmode");
    },
    enumerable: true,
});

/**
 * The Materialize username. Can also come from the `MZ_USERNAME` environment variable.
 */
export declare const username: string | undefined;
Object.defineProperty(exports, "username", {
    get() {
        return __config.get("username");
    },
    enumerable: true,
});

